//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.1.10 in JDK 6 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2016.09.15 at 06:27:29 PM IST 
//


package com.misys.tiplus2.apps.ti.service.custom;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlSchemaType;
import javax.xml.bind.annotation.XmlType;
import javax.xml.datatype.XMLGregorianCalendar;


/**
 * Invoive Details
 * 
 * <p>Java class for ExtEventInvoiveDetailsType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="ExtEventInvoiveDetailsType">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="INVSRNO" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="INVNO" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="INVDATE" type="{http://www.w3.org/2001/XMLSchema}date" minOccurs="0"/>
 *         &lt;element name="FOBAMT" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="INVFRAMT" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="INSUAMT" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="COMMAMT" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="DISCAMT" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="DEDUCAMT" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="PKGAMT" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="INVBILLNO" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="INBLLDAT" type="{http://www.w3.org/2001/XMLSchema}date" minOccurs="0"/>
 *         &lt;element name="INVPRTCD" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="INVAMT" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="FORNO" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "ExtEventInvoiveDetailsType", propOrder = {
    "invsrno",
    "invno",
    "invdate",
    "fobamt",
    "invframt",
    "insuamt",
    "commamt",
    "discamt",
    "deducamt",
    "pkgamt",
    "invbillno",
    "inblldat",
    "invprtcd",
    "invamt",
    "forno"
})
public class ExtEventInvoiveDetailsType {

    @XmlElement(name = "INVSRNO")
    protected String invsrno;
    @XmlElement(name = "INVNO")
    protected String invno;
    @XmlElement(name = "INVDATE")
    @XmlSchemaType(name = "date")
    protected XMLGregorianCalendar invdate;
    @XmlElement(name = "FOBAMT")
    protected String fobamt;
    @XmlElement(name = "INVFRAMT")
    protected String invframt;
    @XmlElement(name = "INSUAMT")
    protected String insuamt;
    @XmlElement(name = "COMMAMT")
    protected String commamt;
    @XmlElement(name = "DISCAMT")
    protected String discamt;
    @XmlElement(name = "DEDUCAMT")
    protected String deducamt;
    @XmlElement(name = "PKGAMT")
    protected String pkgamt;
    @XmlElement(name = "INVBILLNO")
    protected String invbillno;
    @XmlElement(name = "INBLLDAT")
    @XmlSchemaType(name = "date")
    protected XMLGregorianCalendar inblldat;
    @XmlElement(name = "INVPRTCD")
    protected String invprtcd;
    @XmlElement(name = "INVAMT")
    protected String invamt;
    @XmlElement(name = "FORNO")
    protected String forno;

    /**
     * Gets the value of the invsrno property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getINVSRNO() {
        return invsrno;
    }

    /**
     * Sets the value of the invsrno property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setINVSRNO(String value) {
        this.invsrno = value;
    }

    /**
     * Gets the value of the invno property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getINVNO() {
        return invno;
    }

    /**
     * Sets the value of the invno property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setINVNO(String value) {
        this.invno = value;
    }

    /**
     * Gets the value of the invdate property.
     * 
     * @return
     *     possible object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public XMLGregorianCalendar getINVDATE() {
        return invdate;
    }

    /**
     * Sets the value of the invdate property.
     * 
     * @param value
     *     allowed object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public void setINVDATE(XMLGregorianCalendar value) {
        this.invdate = value;
    }

    /**
     * Gets the value of the fobamt property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getFOBAMT() {
        return fobamt;
    }

    /**
     * Sets the value of the fobamt property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setFOBAMT(String value) {
        this.fobamt = value;
    }

    /**
     * Gets the value of the invframt property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getINVFRAMT() {
        return invframt;
    }

    /**
     * Sets the value of the invframt property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setINVFRAMT(String value) {
        this.invframt = value;
    }

    /**
     * Gets the value of the insuamt property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getINSUAMT() {
        return insuamt;
    }

    /**
     * Sets the value of the insuamt property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setINSUAMT(String value) {
        this.insuamt = value;
    }

    /**
     * Gets the value of the commamt property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getCOMMAMT() {
        return commamt;
    }

    /**
     * Sets the value of the commamt property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setCOMMAMT(String value) {
        this.commamt = value;
    }

    /**
     * Gets the value of the discamt property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getDISCAMT() {
        return discamt;
    }

    /**
     * Sets the value of the discamt property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setDISCAMT(String value) {
        this.discamt = value;
    }

    /**
     * Gets the value of the deducamt property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getDEDUCAMT() {
        return deducamt;
    }

    /**
     * Sets the value of the deducamt property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setDEDUCAMT(String value) {
        this.deducamt = value;
    }

    /**
     * Gets the value of the pkgamt property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getPKGAMT() {
        return pkgamt;
    }

    /**
     * Sets the value of the pkgamt property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setPKGAMT(String value) {
        this.pkgamt = value;
    }

    /**
     * Gets the value of the invbillno property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getINVBILLNO() {
        return invbillno;
    }

    /**
     * Sets the value of the invbillno property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setINVBILLNO(String value) {
        this.invbillno = value;
    }

    /**
     * Gets the value of the inblldat property.
     * 
     * @return
     *     possible object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public XMLGregorianCalendar getINBLLDAT() {
        return inblldat;
    }

    /**
     * Sets the value of the inblldat property.
     * 
     * @param value
     *     allowed object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public void setINBLLDAT(XMLGregorianCalendar value) {
        this.inblldat = value;
    }

    /**
     * Gets the value of the invprtcd property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getINVPRTCD() {
        return invprtcd;
    }

    /**
     * Sets the value of the invprtcd property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setINVPRTCD(String value) {
        this.invprtcd = value;
    }

    /**
     * Gets the value of the invamt property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getINVAMT() {
        return invamt;
    }

    /**
     * Sets the value of the invamt property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setINVAMT(String value) {
        this.invamt = value;
    }

    /**
     * Gets the value of the forno property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getFORNO() {
        return forno;
    }

    /**
     * Sets the value of the forno property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setFORNO(String value) {
        this.forno = value;
    }

}
