//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.1.10 in JDK 6 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2016.09.15 at 06:27:29 PM IST 
//


package com.misys.tiplus2.apps.ti.service.custom;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * Share Company Details.
 * 
 * <p>Java class for ExtEventSHARECOMType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="ExtEventSHARECOMType">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="NAMESCM" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="ACTCOMP" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="NICCODE" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="NUMSHAR" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="FACESHAR" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="SALESHAR" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "ExtEventSHARECOMType", propOrder = {
    "namescm",
    "actcomp",
    "niccode",
    "numshar",
    "faceshar",
    "saleshar"
})
public class ExtEventSHARECOMType {

    @XmlElement(name = "NAMESCM")
    protected String namescm;
    @XmlElement(name = "ACTCOMP")
    protected String actcomp;
    @XmlElement(name = "NICCODE")
    protected String niccode;
    @XmlElement(name = "NUMSHAR")
    protected String numshar;
    @XmlElement(name = "FACESHAR")
    protected String faceshar;
    @XmlElement(name = "SALESHAR")
    protected String saleshar;

    /**
     * Gets the value of the namescm property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getNAMESCM() {
        return namescm;
    }

    /**
     * Sets the value of the namescm property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setNAMESCM(String value) {
        this.namescm = value;
    }

    /**
     * Gets the value of the actcomp property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getACTCOMP() {
        return actcomp;
    }

    /**
     * Sets the value of the actcomp property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setACTCOMP(String value) {
        this.actcomp = value;
    }

    /**
     * Gets the value of the niccode property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getNICCODE() {
        return niccode;
    }

    /**
     * Sets the value of the niccode property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setNICCODE(String value) {
        this.niccode = value;
    }

    /**
     * Gets the value of the numshar property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getNUMSHAR() {
        return numshar;
    }

    /**
     * Sets the value of the numshar property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setNUMSHAR(String value) {
        this.numshar = value;
    }

    /**
     * Gets the value of the faceshar property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getFACESHAR() {
        return faceshar;
    }

    /**
     * Sets the value of the faceshar property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setFACESHAR(String value) {
        this.faceshar = value;
    }

    /**
     * Gets the value of the saleshar property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getSALESHAR() {
        return saleshar;
    }

    /**
     * Sets the value of the saleshar property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setSALESHAR(String value) {
        this.saleshar = value;
    }

}
