//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.1.10 in JDK 6 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2016.09.15 at 06:27:29 PM IST 
//


package com.misys.tiplus2.apps.ti.service.custom;

import java.math.BigDecimal;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlSchemaType;
import javax.xml.bind.annotation.XmlType;
import javax.xml.datatype.XMLGregorianCalendar;


/**
 * Shipping Details
 * 
 * <p>Java class for ExtEventShippingdetailsType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="ExtEventShippingdetailsType">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="BILLNO" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="BILLDATE" type="{http://www.w3.org/2001/XMLSchema}date" minOccurs="0"/>
 *         &lt;element name="PORTCODE" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="LEODATE" type="{http://www.w3.org/2001/XMLSchema}date" minOccurs="0"/>
 *         &lt;element name="CUSTNO" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="FORMNO" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="EXPAGENC" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="EXPTYPE" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="DESTCOUN" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="BLLAMT" type="{http://www.w3.org/2001/XMLSchema}decimal" minOccurs="0"/>
 *         &lt;element name="IECODE" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="ADCODE" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="SHICOU" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="DRTIN" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="ADBILN" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="DTNEG" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "ExtEventShippingdetailsType", propOrder = {
    "billno",
    "billdate",
    "portcode",
    "leodate",
    "custno",
    "formno",
    "expagenc",
    "exptype",
    "destcoun",
    "bllamt",
    "iecode",
    "adcode",
    "shicou",
    "drtin",
    "adbiln",
    "dtneg"
})
public class ExtEventShippingdetailsType {

    @XmlElement(name = "BILLNO")
    protected String billno;
    @XmlElement(name = "BILLDATE")
    @XmlSchemaType(name = "date")
    protected XMLGregorianCalendar billdate;
    @XmlElement(name = "PORTCODE")
    protected String portcode;
    @XmlElement(name = "LEODATE")
    @XmlSchemaType(name = "date")
    protected XMLGregorianCalendar leodate;
    @XmlElement(name = "CUSTNO")
    protected String custno;
    @XmlElement(name = "FORMNO")
    protected String formno;
    @XmlElement(name = "EXPAGENC")
    protected String expagenc;
    @XmlElement(name = "EXPTYPE")
    protected String exptype;
    @XmlElement(name = "DESTCOUN")
    protected String destcoun;
    @XmlElement(name = "BLLAMT")
    protected BigDecimal bllamt;
    @XmlElement(name = "IECODE")
    protected String iecode;
    @XmlElement(name = "ADCODE")
    protected String adcode;
    @XmlElement(name = "SHICOU")
    protected String shicou;
    @XmlElement(name = "DRTIN")
    protected String drtin;
    @XmlElement(name = "ADBILN")
    protected String adbiln;
    @XmlElement(name = "DTNEG")
    protected String dtneg;

    /**
     * Gets the value of the billno property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getBILLNO() {
        return billno;
    }

    /**
     * Sets the value of the billno property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setBILLNO(String value) {
        this.billno = value;
    }

    /**
     * Gets the value of the billdate property.
     * 
     * @return
     *     possible object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public XMLGregorianCalendar getBILLDATE() {
        return billdate;
    }

    /**
     * Sets the value of the billdate property.
     * 
     * @param value
     *     allowed object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public void setBILLDATE(XMLGregorianCalendar value) {
        this.billdate = value;
    }

    /**
     * Gets the value of the portcode property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getPORTCODE() {
        return portcode;
    }

    /**
     * Sets the value of the portcode property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setPORTCODE(String value) {
        this.portcode = value;
    }

    /**
     * Gets the value of the leodate property.
     * 
     * @return
     *     possible object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public XMLGregorianCalendar getLEODATE() {
        return leodate;
    }

    /**
     * Sets the value of the leodate property.
     * 
     * @param value
     *     allowed object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public void setLEODATE(XMLGregorianCalendar value) {
        this.leodate = value;
    }

    /**
     * Gets the value of the custno property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getCUSTNO() {
        return custno;
    }

    /**
     * Sets the value of the custno property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setCUSTNO(String value) {
        this.custno = value;
    }

    /**
     * Gets the value of the formno property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getFORMNO() {
        return formno;
    }

    /**
     * Sets the value of the formno property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setFORMNO(String value) {
        this.formno = value;
    }

    /**
     * Gets the value of the expagenc property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getEXPAGENC() {
        return expagenc;
    }

    /**
     * Sets the value of the expagenc property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setEXPAGENC(String value) {
        this.expagenc = value;
    }

    /**
     * Gets the value of the exptype property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getEXPTYPE() {
        return exptype;
    }

    /**
     * Sets the value of the exptype property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setEXPTYPE(String value) {
        this.exptype = value;
    }

    /**
     * Gets the value of the destcoun property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getDESTCOUN() {
        return destcoun;
    }

    /**
     * Sets the value of the destcoun property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setDESTCOUN(String value) {
        this.destcoun = value;
    }

    /**
     * Gets the value of the bllamt property.
     * 
     * @return
     *     possible object is
     *     {@link BigDecimal }
     *     
     */
    public BigDecimal getBLLAMT() {
        return bllamt;
    }

    /**
     * Sets the value of the bllamt property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigDecimal }
     *     
     */
    public void setBLLAMT(BigDecimal value) {
        this.bllamt = value;
    }

    /**
     * Gets the value of the iecode property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getIECODE() {
        return iecode;
    }

    /**
     * Sets the value of the iecode property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setIECODE(String value) {
        this.iecode = value;
    }

    /**
     * Gets the value of the adcode property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getADCODE() {
        return adcode;
    }

    /**
     * Sets the value of the adcode property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setADCODE(String value) {
        this.adcode = value;
    }

    /**
     * Gets the value of the shicou property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getSHICOU() {
        return shicou;
    }

    /**
     * Sets the value of the shicou property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setSHICOU(String value) {
        this.shicou = value;
    }

    /**
     * Gets the value of the drtin property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getDRTIN() {
        return drtin;
    }

    /**
     * Sets the value of the drtin property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setDRTIN(String value) {
        this.drtin = value;
    }

    /**
     * Gets the value of the adbiln property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getADBILN() {
        return adbiln;
    }

    /**
     * Sets the value of the adbiln property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setADBILN(String value) {
        this.adbiln = value;
    }

    /**
     * Gets the value of the dtneg property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getDTNEG() {
        return dtneg;
    }

    /**
     * Sets the value of the dtneg property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setDTNEG(String value) {
        this.dtneg = value;
    }

}
