//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.1.10 in JDK 6 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2016.09.15 at 06:27:29 PM IST 
//


package com.misys.tiplus2.apps.ti.service.custom;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * Under Masters we require ECGC Centre wise Master for capturing details
 * 
 * <p>Java class for ExtEventUMECGCType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="ExtEventUMECGCType">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="UMNAME" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="UMADDR" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="ACCNO" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="ROUDE" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="ROUBN" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="IFSCC" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "ExtEventUMECGCType", propOrder = {
    "umname",
    "umaddr",
    "accno",
    "roude",
    "roubn",
    "ifscc"
})
public class ExtEventUMECGCType {

    @XmlElement(name = "UMNAME")
    protected String umname;
    @XmlElement(name = "UMADDR")
    protected String umaddr;
    @XmlElement(name = "ACCNO")
    protected String accno;
    @XmlElement(name = "ROUDE")
    protected String roude;
    @XmlElement(name = "ROUBN")
    protected String roubn;
    @XmlElement(name = "IFSCC")
    protected String ifscc;

    /**
     * Gets the value of the umname property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getUMNAME() {
        return umname;
    }

    /**
     * Sets the value of the umname property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setUMNAME(String value) {
        this.umname = value;
    }

    /**
     * Gets the value of the umaddr property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getUMADDR() {
        return umaddr;
    }

    /**
     * Sets the value of the umaddr property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setUMADDR(String value) {
        this.umaddr = value;
    }

    /**
     * Gets the value of the accno property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getACCNO() {
        return accno;
    }

    /**
     * Sets the value of the accno property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setACCNO(String value) {
        this.accno = value;
    }

    /**
     * Gets the value of the roude property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getROUDE() {
        return roude;
    }

    /**
     * Sets the value of the roude property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setROUDE(String value) {
        this.roude = value;
    }

    /**
     * Gets the value of the roubn property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getROUBN() {
        return roubn;
    }

    /**
     * Sets the value of the roubn property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setROUBN(String value) {
        this.roubn = value;
    }

    /**
     * Gets the value of the ifscc property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getIFSCC() {
        return ifscc;
    }

    /**
     * Sets the value of the ifscc property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setIFSCC(String value) {
        this.ifscc = value;
    }

}
