//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.1.10 in JDK 6 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2016.09.15 at 06:27:29 PM IST 
//


package com.misys.tiplus2.apps.ti.service.custom;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * DOCUMENTS 1
 * 
 * <p>Java class for ExtEventDOCUMENTAType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="ExtEventDOCUMENTAType">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="DOCODE" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="ORIG" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="COPE" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "ExtEventDOCUMENTAType", propOrder = {
    "docode",
    "orig",
    "cope"
})
public class ExtEventDOCUMENTAType {

    @XmlElement(name = "DOCODE")
    protected String docode;
    @XmlElement(name = "ORIG")
    protected String orig;
    @XmlElement(name = "COPE")
    protected String cope;

    /**
     * Gets the value of the docode property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getDOCODE() {
        return docode;
    }

    /**
     * Sets the value of the docode property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setDOCODE(String value) {
        this.docode = value;
    }

    /**
     * Gets the value of the orig property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getORIG() {
        return orig;
    }

    /**
     * Sets the value of the orig property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setORIG(String value) {
        this.orig = value;
    }

    /**
     * Gets the value of the cope property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getCOPE() {
        return cope;
    }

    /**
     * Sets the value of the cope property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setCOPE(String value) {
        this.cope = value;
    }

}
