//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2020.03.16 at 05:37:19 PM IST 
//


package com.boc.customerinquiryrequest;

import javax.xml.bind.annotation.XmlRegistry;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the com.boc.CustomerInquiryRequest package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {


    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: com.boc.CustomerInquiryRequest
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link IFX }
     * 
     */
    public IFX createIFX() {
        return new IFX();
    }

    /**
     * Create an instance of {@link IFX.CIFSvcRq }
     * 
     */
    public IFX.CIFSvcRq createIFXCIFSvcRq() {
        return new IFX.CIFSvcRq();
    }

    /**
     * Create an instance of {@link IFX.CIFSvcRq.CustProfBasicInqRq }
     * 
     */
    public IFX.CIFSvcRq.CustProfBasicInqRq createIFXCIFSvcRqCustProfBasicInqRq() {
        return new IFX.CIFSvcRq.CustProfBasicInqRq();
    }

    /**
     * Create an instance of {@link IFX.SignonRq }
     * 
     */
    public IFX.SignonRq createIFXSignonRq() {
        return new IFX.SignonRq();
    }

    /**
     * Create an instance of {@link IFX.SignonRq.SignonPswd }
     * 
     */
    public IFX.SignonRq.SignonPswd createIFXSignonRqSignonPswd() {
        return new IFX.SignonRq.SignonPswd();
    }

    /**
     * Create an instance of {@link IFX.EnvironmentInfo }
     * 
     */
    public IFX.EnvironmentInfo createIFXEnvironmentInfo() {
        return new IFX.EnvironmentInfo();
    }

    /**
     * Create an instance of {@link IFX.CIFSvcRq.CustProfBasicInqRq.CustId }
     * 
     */
    public IFX.CIFSvcRq.CustProfBasicInqRq.CustId createIFXCIFSvcRqCustProfBasicInqRqCustId() {
        return new IFX.CIFSvcRq.CustProfBasicInqRq.CustId();
    }

    /**
     * Create an instance of {@link IFX.SignonRq.ClientApp }
     * 
     */
    public IFX.SignonRq.ClientApp createIFXSignonRqClientApp() {
        return new IFX.SignonRq.ClientApp();
    }

    /**
     * Create an instance of {@link IFX.SignonRq.SignonPswd.CustId }
     * 
     */
    public IFX.SignonRq.SignonPswd.CustId createIFXSignonRqSignonPswdCustId() {
        return new IFX.SignonRq.SignonPswd.CustId();
    }

    /**
     * Create an instance of {@link IFX.SignonRq.SignonPswd.CustPswd }
     * 
     */
    public IFX.SignonRq.SignonPswd.CustPswd createIFXSignonRqSignonPswdCustPswd() {
        return new IFX.SignonRq.SignonPswd.CustPswd();
    }

}
