//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2020.03.18 at 04:25:58 PM IST 
//


package com.boc.accountcustomerresponse;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="GeneralStatus">
 *           &lt;complexType>
 *             &lt;complexContent>
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                 &lt;sequence>
 *                   &lt;element name="StatusCode" type="{http://www.w3.org/2001/XMLSchema}byte"/>
 *                   &lt;element name="StatusLevel" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                   &lt;element name="StatusDesc" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                 &lt;/sequence>
 *               &lt;/restriction>
 *             &lt;/complexContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *         &lt;element name="Status">
 *           &lt;complexType>
 *             &lt;complexContent>
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                 &lt;sequence>
 *                   &lt;element name="StatusCode" type="{http://www.w3.org/2001/XMLSchema}byte"/>
 *                   &lt;element name="Severity" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                   &lt;element name="StatusDesc" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                   &lt;element name="SupportUID" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                 &lt;/sequence>
 *               &lt;/restriction>
 *             &lt;/complexContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *         &lt;element name="SignonRs">
 *           &lt;complexType>
 *             &lt;complexContent>
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                 &lt;sequence>
 *                   &lt;element name="Status">
 *                     &lt;complexType>
 *                       &lt;complexContent>
 *                         &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                           &lt;sequence>
 *                             &lt;element name="StatusCode" type="{http://www.w3.org/2001/XMLSchema}byte"/>
 *                             &lt;element name="Severity" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                             &lt;element name="StatusDesc" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                             &lt;element name="SupportUID" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                           &lt;/sequence>
 *                         &lt;/restriction>
 *                       &lt;/complexContent>
 *                     &lt;/complexType>
 *                   &lt;/element>
 *                   &lt;element name="SignonRole" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                   &lt;element name="CustId">
 *                     &lt;complexType>
 *                       &lt;complexContent>
 *                         &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                           &lt;sequence>
 *                             &lt;element name="SPName" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                             &lt;element name="CustLoginId" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                           &lt;/sequence>
 *                         &lt;/restriction>
 *                       &lt;/complexContent>
 *                     &lt;/complexType>
 *                   &lt;/element>
 *                   &lt;element name="GenSessKey" type="{http://www.w3.org/2001/XMLSchema}byte"/>
 *                   &lt;element name="ClientDt">
 *                     &lt;complexType>
 *                       &lt;complexContent>
 *                         &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                           &lt;sequence>
 *                             &lt;element name="Year" type="{http://www.w3.org/2001/XMLSchema}short"/>
 *                             &lt;element name="Month" type="{http://www.w3.org/2001/XMLSchema}byte"/>
 *                             &lt;element name="Day" type="{http://www.w3.org/2001/XMLSchema}byte"/>
 *                           &lt;/sequence>
 *                         &lt;/restriction>
 *                       &lt;/complexContent>
 *                     &lt;/complexType>
 *                   &lt;/element>
 *                   &lt;element name="CustLangPref" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                   &lt;element name="ClientApp">
 *                     &lt;complexType>
 *                       &lt;complexContent>
 *                         &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                           &lt;sequence>
 *                             &lt;element name="Org" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                             &lt;element name="Name" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                             &lt;element name="Version" type="{http://www.w3.org/2001/XMLSchema}float"/>
 *                             &lt;element name="ClientAppKey" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                           &lt;/sequence>
 *                         &lt;/restriction>
 *                       &lt;/complexContent>
 *                     &lt;/complexType>
 *                   &lt;/element>
 *                   &lt;element name="ServerDt">
 *                     &lt;complexType>
 *                       &lt;complexContent>
 *                         &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                           &lt;sequence>
 *                             &lt;element name="Year" type="{http://www.w3.org/2001/XMLSchema}short"/>
 *                             &lt;element name="Month" type="{http://www.w3.org/2001/XMLSchema}byte"/>
 *                             &lt;element name="Day" type="{http://www.w3.org/2001/XMLSchema}byte"/>
 *                             &lt;element name="Hour" type="{http://www.w3.org/2001/XMLSchema}byte"/>
 *                             &lt;element name="Minute" type="{http://www.w3.org/2001/XMLSchema}byte"/>
 *                             &lt;element name="Second" type="{http://www.w3.org/2001/XMLSchema}byte"/>
 *                             &lt;element name="Fraction" type="{http://www.w3.org/2001/XMLSchema}int"/>
 *                             &lt;element name="UTCOffset" type="{http://www.w3.org/2001/XMLSchema}short"/>
 *                           &lt;/sequence>
 *                         &lt;/restriction>
 *                       &lt;/complexContent>
 *                     &lt;/complexType>
 *                   &lt;/element>
 *                   &lt;element name="Language" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                   &lt;element name="ComputerKey" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                   &lt;element name="PersonName">
 *                     &lt;complexType>
 *                       &lt;complexContent>
 *                         &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                           &lt;sequence>
 *                             &lt;element name="LastName" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                             &lt;element name="FirstName" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                           &lt;/sequence>
 *                         &lt;/restriction>
 *                       &lt;/complexContent>
 *                     &lt;/complexType>
 *                   &lt;/element>
 *                 &lt;/sequence>
 *               &lt;/restriction>
 *             &lt;/complexContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *         &lt;element name="EnvironmentInfo">
 *           &lt;complexType>
 *             &lt;complexContent>
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                 &lt;sequence>
 *                   &lt;element name="EnvironmentName" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                 &lt;/sequence>
 *               &lt;/restriction>
 *             &lt;/complexContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *         &lt;element name="MaintSvcRs">
 *           &lt;complexType>
 *             &lt;complexContent>
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                 &lt;sequence>
 *                   &lt;element name="Status">
 *                     &lt;complexType>
 *                       &lt;complexContent>
 *                         &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                           &lt;sequence>
 *                             &lt;element name="StatusCode" type="{http://www.w3.org/2001/XMLSchema}byte"/>
 *                             &lt;element name="Severity" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                             &lt;element name="StatusDesc" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                             &lt;element name="SupportUID" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                           &lt;/sequence>
 *                         &lt;/restriction>
 *                       &lt;/complexContent>
 *                     &lt;/complexType>
 *                   &lt;/element>
 *                   &lt;element name="RqUID" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                   &lt;element name="SPName" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                   &lt;element name="Version" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                   &lt;element name="AcctCustInqRs">
 *                     &lt;complexType>
 *                       &lt;complexContent>
 *                         &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                           &lt;sequence>
 *                             &lt;element name="Status">
 *                               &lt;complexType>
 *                                 &lt;complexContent>
 *                                   &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                                     &lt;sequence>
 *                                       &lt;element name="StatusCode" type="{http://www.w3.org/2001/XMLSchema}byte"/>
 *                                       &lt;element name="Severity" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                                       &lt;element name="StatusDesc" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                                       &lt;element name="SupportUID" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                                     &lt;/sequence>
 *                                   &lt;/restriction>
 *                                 &lt;/complexContent>
 *                               &lt;/complexType>
 *                             &lt;/element>
 *                             &lt;element name="RqUID" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                             &lt;element name="RecCtrlOut">
 *                               &lt;complexType>
 *                                 &lt;complexContent>
 *                                   &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                                     &lt;sequence>
 *                                       &lt;element name="MatchedRec" type="{http://www.w3.org/2001/XMLSchema}byte"/>
 *                                       &lt;element name="SentRec" type="{http://www.w3.org/2001/XMLSchema}byte"/>
 *                                     &lt;/sequence>
 *                                   &lt;/restriction>
 *                                 &lt;/complexContent>
 *                               &lt;/complexType>
 *                             &lt;/element>
 *                             &lt;element name="AcctRelation">
 *                               &lt;complexType>
 *                                 &lt;complexContent>
 *                                   &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                                     &lt;sequence>
 *                                       &lt;element name="RelationCode" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                                       &lt;element name="CustPermId" type="{http://www.w3.org/2001/XMLSchema}int"/>
 *                                       &lt;element name="FullName" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                                       &lt;element name="TaxLiabilityPctAmt" type="{http://www.w3.org/2001/XMLSchema}float"/>
 *                                     &lt;/sequence>
 *                                   &lt;/restriction>
 *                                 &lt;/complexContent>
 *                               &lt;/complexType>
 *                             &lt;/element>
 *                           &lt;/sequence>
 *                         &lt;/restriction>
 *                       &lt;/complexContent>
 *                     &lt;/complexType>
 *                   &lt;/element>
 *                 &lt;/sequence>
 *               &lt;/restriction>
 *             &lt;/complexContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "generalStatus",
    "status",
    "signonRs",
    "environmentInfo",
    "maintSvcRs"
})
@XmlRootElement(name = "IFX")
public class IFX {

    @XmlElement(name = "GeneralStatus", required = true)
    protected IFX.GeneralStatus generalStatus;
    @XmlElement(name = "Status", required = true)
    protected IFX.Status status;
    @XmlElement(name = "SignonRs", required = true)
    protected IFX.SignonRs signonRs;
    @XmlElement(name = "EnvironmentInfo", required = true)
    protected IFX.EnvironmentInfo environmentInfo;
    @XmlElement(name = "MaintSvcRs", required = true)
    protected IFX.MaintSvcRs maintSvcRs;

    /**
     * Gets the value of the generalStatus property.
     * 
     * @return
     *     possible object is
     *     {@link IFX.GeneralStatus }
     *     
     */
    public IFX.GeneralStatus getGeneralStatus() {
        return generalStatus;
    }

    /**
     * Sets the value of the generalStatus property.
     * 
     * @param value
     *     allowed object is
     *     {@link IFX.GeneralStatus }
     *     
     */
    public void setGeneralStatus(IFX.GeneralStatus value) {
        this.generalStatus = value;
    }

    /**
     * Gets the value of the status property.
     * 
     * @return
     *     possible object is
     *     {@link IFX.Status }
     *     
     */
    public IFX.Status getStatus() {
        return status;
    }

    /**
     * Sets the value of the status property.
     * 
     * @param value
     *     allowed object is
     *     {@link IFX.Status }
     *     
     */
    public void setStatus(IFX.Status value) {
        this.status = value;
    }

    /**
     * Gets the value of the signonRs property.
     * 
     * @return
     *     possible object is
     *     {@link IFX.SignonRs }
     *     
     */
    public IFX.SignonRs getSignonRs() {
        return signonRs;
    }

    /**
     * Sets the value of the signonRs property.
     * 
     * @param value
     *     allowed object is
     *     {@link IFX.SignonRs }
     *     
     */
    public void setSignonRs(IFX.SignonRs value) {
        this.signonRs = value;
    }

    /**
     * Gets the value of the environmentInfo property.
     * 
     * @return
     *     possible object is
     *     {@link IFX.EnvironmentInfo }
     *     
     */
    public IFX.EnvironmentInfo getEnvironmentInfo() {
        return environmentInfo;
    }

    /**
     * Sets the value of the environmentInfo property.
     * 
     * @param value
     *     allowed object is
     *     {@link IFX.EnvironmentInfo }
     *     
     */
    public void setEnvironmentInfo(IFX.EnvironmentInfo value) {
        this.environmentInfo = value;
    }

    /**
     * Gets the value of the maintSvcRs property.
     * 
     * @return
     *     possible object is
     *     {@link IFX.MaintSvcRs }
     *     
     */
    public IFX.MaintSvcRs getMaintSvcRs() {
        return maintSvcRs;
    }

    /**
     * Sets the value of the maintSvcRs property.
     * 
     * @param value
     *     allowed object is
     *     {@link IFX.MaintSvcRs }
     *     
     */
    public void setMaintSvcRs(IFX.MaintSvcRs value) {
        this.maintSvcRs = value;
    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType>
     *   &lt;complexContent>
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *       &lt;sequence>
     *         &lt;element name="EnvironmentName" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *       &lt;/sequence>
     *     &lt;/restriction>
     *   &lt;/complexContent>
     * &lt;/complexType>
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "environmentName"
    })
    public static class EnvironmentInfo {

        @XmlElement(name = "EnvironmentName", required = true)
        protected String environmentName;

        /**
         * Gets the value of the environmentName property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getEnvironmentName() {
            return environmentName;
        }

        /**
         * Sets the value of the environmentName property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setEnvironmentName(String value) {
            this.environmentName = value;
        }

    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType>
     *   &lt;complexContent>
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *       &lt;sequence>
     *         &lt;element name="StatusCode" type="{http://www.w3.org/2001/XMLSchema}byte"/>
     *         &lt;element name="StatusLevel" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *         &lt;element name="StatusDesc" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *       &lt;/sequence>
     *     &lt;/restriction>
     *   &lt;/complexContent>
     * &lt;/complexType>
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "statusCode",
        "statusLevel",
        "statusDesc"
    })
    public static class GeneralStatus {

        @XmlElement(name = "StatusCode")
        protected byte statusCode;
        @XmlElement(name = "StatusLevel", required = true)
        protected String statusLevel;
        @XmlElement(name = "StatusDesc", required = true)
        protected String statusDesc;

        /**
         * Gets the value of the statusCode property.
         * 
         */
        public byte getStatusCode() {
            return statusCode;
        }

        /**
         * Sets the value of the statusCode property.
         * 
         */
        public void setStatusCode(byte value) {
            this.statusCode = value;
        }

        /**
         * Gets the value of the statusLevel property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getStatusLevel() {
            return statusLevel;
        }

        /**
         * Sets the value of the statusLevel property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setStatusLevel(String value) {
            this.statusLevel = value;
        }

        /**
         * Gets the value of the statusDesc property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getStatusDesc() {
            return statusDesc;
        }

        /**
         * Sets the value of the statusDesc property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setStatusDesc(String value) {
            this.statusDesc = value;
        }

    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType>
     *   &lt;complexContent>
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *       &lt;sequence>
     *         &lt;element name="Status">
     *           &lt;complexType>
     *             &lt;complexContent>
     *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *                 &lt;sequence>
     *                   &lt;element name="StatusCode" type="{http://www.w3.org/2001/XMLSchema}byte"/>
     *                   &lt;element name="Severity" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *                   &lt;element name="StatusDesc" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *                   &lt;element name="SupportUID" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *                 &lt;/sequence>
     *               &lt;/restriction>
     *             &lt;/complexContent>
     *           &lt;/complexType>
     *         &lt;/element>
     *         &lt;element name="RqUID" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *         &lt;element name="SPName" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *         &lt;element name="Version" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *         &lt;element name="AcctCustInqRs">
     *           &lt;complexType>
     *             &lt;complexContent>
     *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *                 &lt;sequence>
     *                   &lt;element name="Status">
     *                     &lt;complexType>
     *                       &lt;complexContent>
     *                         &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *                           &lt;sequence>
     *                             &lt;element name="StatusCode" type="{http://www.w3.org/2001/XMLSchema}byte"/>
     *                             &lt;element name="Severity" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *                             &lt;element name="StatusDesc" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *                             &lt;element name="SupportUID" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *                           &lt;/sequence>
     *                         &lt;/restriction>
     *                       &lt;/complexContent>
     *                     &lt;/complexType>
     *                   &lt;/element>
     *                   &lt;element name="RqUID" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *                   &lt;element name="RecCtrlOut">
     *                     &lt;complexType>
     *                       &lt;complexContent>
     *                         &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *                           &lt;sequence>
     *                             &lt;element name="MatchedRec" type="{http://www.w3.org/2001/XMLSchema}byte"/>
     *                             &lt;element name="SentRec" type="{http://www.w3.org/2001/XMLSchema}byte"/>
     *                           &lt;/sequence>
     *                         &lt;/restriction>
     *                       &lt;/complexContent>
     *                     &lt;/complexType>
     *                   &lt;/element>
     *                   &lt;element name="AcctRelation">
     *                     &lt;complexType>
     *                       &lt;complexContent>
     *                         &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *                           &lt;sequence>
     *                             &lt;element name="RelationCode" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *                             &lt;element name="CustPermId" type="{http://www.w3.org/2001/XMLSchema}int"/>
     *                             &lt;element name="FullName" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *                             &lt;element name="TaxLiabilityPctAmt" type="{http://www.w3.org/2001/XMLSchema}float"/>
     *                           &lt;/sequence>
     *                         &lt;/restriction>
     *                       &lt;/complexContent>
     *                     &lt;/complexType>
     *                   &lt;/element>
     *                 &lt;/sequence>
     *               &lt;/restriction>
     *             &lt;/complexContent>
     *           &lt;/complexType>
     *         &lt;/element>
     *       &lt;/sequence>
     *     &lt;/restriction>
     *   &lt;/complexContent>
     * &lt;/complexType>
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "status",
        "rqUID",
        "spName",
        "version",
        "acctCustInqRs"
    })
    public static class MaintSvcRs {

        @XmlElement(name = "Status", required = true)
        protected IFX.MaintSvcRs.Status status;
        @XmlElement(name = "RqUID", required = true)
        protected String rqUID;
        @XmlElement(name = "SPName", required = true)
        protected String spName;
        @XmlElement(name = "Version", required = true)
        protected String version;
        @XmlElement(name = "AcctCustInqRs", required = true)
        protected IFX.MaintSvcRs.AcctCustInqRs acctCustInqRs;

        /**
         * Gets the value of the status property.
         * 
         * @return
         *     possible object is
         *     {@link IFX.MaintSvcRs.Status }
         *     
         */
        public IFX.MaintSvcRs.Status getStatus() {
            return status;
        }

        /**
         * Sets the value of the status property.
         * 
         * @param value
         *     allowed object is
         *     {@link IFX.MaintSvcRs.Status }
         *     
         */
        public void setStatus(IFX.MaintSvcRs.Status value) {
            this.status = value;
        }

        /**
         * Gets the value of the rqUID property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getRqUID() {
            return rqUID;
        }

        /**
         * Sets the value of the rqUID property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setRqUID(String value) {
            this.rqUID = value;
        }

        /**
         * Gets the value of the spName property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getSPName() {
            return spName;
        }

        /**
         * Sets the value of the spName property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setSPName(String value) {
            this.spName = value;
        }

        /**
         * Gets the value of the version property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getVersion() {
            return version;
        }

        /**
         * Sets the value of the version property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setVersion(String value) {
            this.version = value;
        }

        /**
         * Gets the value of the acctCustInqRs property.
         * 
         * @return
         *     possible object is
         *     {@link IFX.MaintSvcRs.AcctCustInqRs }
         *     
         */
        public IFX.MaintSvcRs.AcctCustInqRs getAcctCustInqRs() {
            return acctCustInqRs;
        }

        /**
         * Sets the value of the acctCustInqRs property.
         * 
         * @param value
         *     allowed object is
         *     {@link IFX.MaintSvcRs.AcctCustInqRs }
         *     
         */
        public void setAcctCustInqRs(IFX.MaintSvcRs.AcctCustInqRs value) {
            this.acctCustInqRs = value;
        }


        /**
         * <p>Java class for anonymous complex type.
         * 
         * <p>The following schema fragment specifies the expected content contained within this class.
         * 
         * <pre>
         * &lt;complexType>
         *   &lt;complexContent>
         *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
         *       &lt;sequence>
         *         &lt;element name="Status">
         *           &lt;complexType>
         *             &lt;complexContent>
         *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
         *                 &lt;sequence>
         *                   &lt;element name="StatusCode" type="{http://www.w3.org/2001/XMLSchema}byte"/>
         *                   &lt;element name="Severity" type="{http://www.w3.org/2001/XMLSchema}string"/>
         *                   &lt;element name="StatusDesc" type="{http://www.w3.org/2001/XMLSchema}string"/>
         *                   &lt;element name="SupportUID" type="{http://www.w3.org/2001/XMLSchema}string"/>
         *                 &lt;/sequence>
         *               &lt;/restriction>
         *             &lt;/complexContent>
         *           &lt;/complexType>
         *         &lt;/element>
         *         &lt;element name="RqUID" type="{http://www.w3.org/2001/XMLSchema}string"/>
         *         &lt;element name="RecCtrlOut">
         *           &lt;complexType>
         *             &lt;complexContent>
         *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
         *                 &lt;sequence>
         *                   &lt;element name="MatchedRec" type="{http://www.w3.org/2001/XMLSchema}byte"/>
         *                   &lt;element name="SentRec" type="{http://www.w3.org/2001/XMLSchema}byte"/>
         *                 &lt;/sequence>
         *               &lt;/restriction>
         *             &lt;/complexContent>
         *           &lt;/complexType>
         *         &lt;/element>
         *         &lt;element name="AcctRelation">
         *           &lt;complexType>
         *             &lt;complexContent>
         *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
         *                 &lt;sequence>
         *                   &lt;element name="RelationCode" type="{http://www.w3.org/2001/XMLSchema}string"/>
         *                   &lt;element name="CustPermId" type="{http://www.w3.org/2001/XMLSchema}int"/>
         *                   &lt;element name="FullName" type="{http://www.w3.org/2001/XMLSchema}string"/>
         *                   &lt;element name="TaxLiabilityPctAmt" type="{http://www.w3.org/2001/XMLSchema}float"/>
         *                 &lt;/sequence>
         *               &lt;/restriction>
         *             &lt;/complexContent>
         *           &lt;/complexType>
         *         &lt;/element>
         *       &lt;/sequence>
         *     &lt;/restriction>
         *   &lt;/complexContent>
         * &lt;/complexType>
         * </pre>
         * 
         * 
         */
        @XmlAccessorType(XmlAccessType.FIELD)
        @XmlType(name = "", propOrder = {
            "status",
            "rqUID",
            "recCtrlOut",
            "acctRelation"
        })
        public static class AcctCustInqRs {

            @XmlElement(name = "Status", required = true)
            protected IFX.MaintSvcRs.AcctCustInqRs.Status status;
            @XmlElement(name = "RqUID", required = true)
            protected String rqUID;
            @XmlElement(name = "RecCtrlOut", required = true)
            protected IFX.MaintSvcRs.AcctCustInqRs.RecCtrlOut recCtrlOut;
            @XmlElement(name = "AcctRelation", required = true)
            protected IFX.MaintSvcRs.AcctCustInqRs.AcctRelation acctRelation;

            /**
             * Gets the value of the status property.
             * 
             * @return
             *     possible object is
             *     {@link IFX.MaintSvcRs.AcctCustInqRs.Status }
             *     
             */
            public IFX.MaintSvcRs.AcctCustInqRs.Status getStatus() {
                return status;
            }

            /**
             * Sets the value of the status property.
             * 
             * @param value
             *     allowed object is
             *     {@link IFX.MaintSvcRs.AcctCustInqRs.Status }
             *     
             */
            public void setStatus(IFX.MaintSvcRs.AcctCustInqRs.Status value) {
                this.status = value;
            }

            /**
             * Gets the value of the rqUID property.
             * 
             * @return
             *     possible object is
             *     {@link String }
             *     
             */
            public String getRqUID() {
                return rqUID;
            }

            /**
             * Sets the value of the rqUID property.
             * 
             * @param value
             *     allowed object is
             *     {@link String }
             *     
             */
            public void setRqUID(String value) {
                this.rqUID = value;
            }

            /**
             * Gets the value of the recCtrlOut property.
             * 
             * @return
             *     possible object is
             *     {@link IFX.MaintSvcRs.AcctCustInqRs.RecCtrlOut }
             *     
             */
            public IFX.MaintSvcRs.AcctCustInqRs.RecCtrlOut getRecCtrlOut() {
                return recCtrlOut;
            }

            /**
             * Sets the value of the recCtrlOut property.
             * 
             * @param value
             *     allowed object is
             *     {@link IFX.MaintSvcRs.AcctCustInqRs.RecCtrlOut }
             *     
             */
            public void setRecCtrlOut(IFX.MaintSvcRs.AcctCustInqRs.RecCtrlOut value) {
                this.recCtrlOut = value;
            }

            /**
             * Gets the value of the acctRelation property.
             * 
             * @return
             *     possible object is
             *     {@link IFX.MaintSvcRs.AcctCustInqRs.AcctRelation }
             *     
             */
            public IFX.MaintSvcRs.AcctCustInqRs.AcctRelation getAcctRelation() {
                return acctRelation;
            }

            /**
             * Sets the value of the acctRelation property.
             * 
             * @param value
             *     allowed object is
             *     {@link IFX.MaintSvcRs.AcctCustInqRs.AcctRelation }
             *     
             */
            public void setAcctRelation(IFX.MaintSvcRs.AcctCustInqRs.AcctRelation value) {
                this.acctRelation = value;
            }


            /**
             * <p>Java class for anonymous complex type.
             * 
             * <p>The following schema fragment specifies the expected content contained within this class.
             * 
             * <pre>
             * &lt;complexType>
             *   &lt;complexContent>
             *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
             *       &lt;sequence>
             *         &lt;element name="RelationCode" type="{http://www.w3.org/2001/XMLSchema}string"/>
             *         &lt;element name="CustPermId" type="{http://www.w3.org/2001/XMLSchema}int"/>
             *         &lt;element name="FullName" type="{http://www.w3.org/2001/XMLSchema}string"/>
             *         &lt;element name="TaxLiabilityPctAmt" type="{http://www.w3.org/2001/XMLSchema}float"/>
             *       &lt;/sequence>
             *     &lt;/restriction>
             *   &lt;/complexContent>
             * &lt;/complexType>
             * </pre>
             * 
             * 
             */
            @XmlAccessorType(XmlAccessType.FIELD)
            @XmlType(name = "", propOrder = {
                "relationCode",
                "custPermId",
                "fullName",
                "taxLiabilityPctAmt"
            })
            public static class AcctRelation {

                @XmlElement(name = "RelationCode", required = true)
                protected String relationCode;
                @XmlElement(name = "CustPermId")
                protected String custPermId;
                @XmlElement(name = "FullName", required = true)
                protected String fullName;
                @XmlElement(name = "TaxLiabilityPctAmt")
                protected float taxLiabilityPctAmt;

                /**
                 * Gets the value of the relationCode property.
                 * 
                 * @return
                 *     possible object is
                 *     {@link String }
                 *     
                 */
                public String getRelationCode() {
                    return relationCode;
                }

                /**
                 * Sets the value of the relationCode property.
                 * 
                 * @param value
                 *     allowed object is
                 *     {@link String }
                 *     
                 */
                public void setRelationCode(String value) {
                    this.relationCode = value;
                }

                /**
                 * Gets the value of the custPermId property.
                 * 
                 */
                public String getCustPermId() {
                    return custPermId;
                }

                /**
                 * Sets the value of the custPermId property.
                 * 
                 */
                public void setCustPermId(String value) {
                    this.custPermId = value;
                }

                /**
                 * Gets the value of the fullName property.
                 * 
                 * @return
                 *     possible object is
                 *     {@link String }
                 *     
                 */
                public String getFullName() {
                    return fullName;
                }

                /**
                 * Sets the value of the fullName property.
                 * 
                 * @param value
                 *     allowed object is
                 *     {@link String }
                 *     
                 */
                public void setFullName(String value) {
                    this.fullName = value;
                }

                /**
                 * Gets the value of the taxLiabilityPctAmt property.
                 * 
                 */
                public float getTaxLiabilityPctAmt() {
                    return taxLiabilityPctAmt;
                }

                /**
                 * Sets the value of the taxLiabilityPctAmt property.
                 * 
                 */
                public void setTaxLiabilityPctAmt(float value) {
                    this.taxLiabilityPctAmt = value;
                }

            }


            /**
             * <p>Java class for anonymous complex type.
             * 
             * <p>The following schema fragment specifies the expected content contained within this class.
             * 
             * <pre>
             * &lt;complexType>
             *   &lt;complexContent>
             *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
             *       &lt;sequence>
             *         &lt;element name="MatchedRec" type="{http://www.w3.org/2001/XMLSchema}byte"/>
             *         &lt;element name="SentRec" type="{http://www.w3.org/2001/XMLSchema}byte"/>
             *       &lt;/sequence>
             *     &lt;/restriction>
             *   &lt;/complexContent>
             * &lt;/complexType>
             * </pre>
             * 
             * 
             */
            @XmlAccessorType(XmlAccessType.FIELD)
            @XmlType(name = "", propOrder = {
                "matchedRec",
                "sentRec"
            })
            public static class RecCtrlOut {

                @XmlElement(name = "MatchedRec")
                protected byte matchedRec;
                @XmlElement(name = "SentRec")
                protected byte sentRec;

                /**
                 * Gets the value of the matchedRec property.
                 * 
                 */
                public byte getMatchedRec() {
                    return matchedRec;
                }

                /**
                 * Sets the value of the matchedRec property.
                 * 
                 */
                public void setMatchedRec(byte value) {
                    this.matchedRec = value;
                }

                /**
                 * Gets the value of the sentRec property.
                 * 
                 */
                public byte getSentRec() {
                    return sentRec;
                }

                /**
                 * Sets the value of the sentRec property.
                 * 
                 */
                public void setSentRec(byte value) {
                    this.sentRec = value;
                }

            }


            /**
             * <p>Java class for anonymous complex type.
             * 
             * <p>The following schema fragment specifies the expected content contained within this class.
             * 
             * <pre>
             * &lt;complexType>
             *   &lt;complexContent>
             *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
             *       &lt;sequence>
             *         &lt;element name="StatusCode" type="{http://www.w3.org/2001/XMLSchema}byte"/>
             *         &lt;element name="Severity" type="{http://www.w3.org/2001/XMLSchema}string"/>
             *         &lt;element name="StatusDesc" type="{http://www.w3.org/2001/XMLSchema}string"/>
             *         &lt;element name="SupportUID" type="{http://www.w3.org/2001/XMLSchema}string"/>
             *       &lt;/sequence>
             *     &lt;/restriction>
             *   &lt;/complexContent>
             * &lt;/complexType>
             * </pre>
             * 
             * 
             */
            @XmlAccessorType(XmlAccessType.FIELD)
            @XmlType(name = "", propOrder = {
                "statusCode",
                "severity",
                "statusDesc",
                "supportUID"
            })
            public static class Status {

                @XmlElement(name = "StatusCode")
                protected byte statusCode;
                @XmlElement(name = "Severity", required = true)
                protected String severity;
                @XmlElement(name = "StatusDesc", required = true)
                protected String statusDesc;
                @XmlElement(name = "SupportUID", required = true)
                protected String supportUID;

                /**
                 * Gets the value of the statusCode property.
                 * 
                 */
                public byte getStatusCode() {
                    return statusCode;
                }

                /**
                 * Sets the value of the statusCode property.
                 * 
                 */
                public void setStatusCode(byte value) {
                    this.statusCode = value;
                }

                /**
                 * Gets the value of the severity property.
                 * 
                 * @return
                 *     possible object is
                 *     {@link String }
                 *     
                 */
                public String getSeverity() {
                    return severity;
                }

                /**
                 * Sets the value of the severity property.
                 * 
                 * @param value
                 *     allowed object is
                 *     {@link String }
                 *     
                 */
                public void setSeverity(String value) {
                    this.severity = value;
                }

                /**
                 * Gets the value of the statusDesc property.
                 * 
                 * @return
                 *     possible object is
                 *     {@link String }
                 *     
                 */
                public String getStatusDesc() {
                    return statusDesc;
                }

                /**
                 * Sets the value of the statusDesc property.
                 * 
                 * @param value
                 *     allowed object is
                 *     {@link String }
                 *     
                 */
                public void setStatusDesc(String value) {
                    this.statusDesc = value;
                }

                /**
                 * Gets the value of the supportUID property.
                 * 
                 * @return
                 *     possible object is
                 *     {@link String }
                 *     
                 */
                public String getSupportUID() {
                    return supportUID;
                }

                /**
                 * Sets the value of the supportUID property.
                 * 
                 * @param value
                 *     allowed object is
                 *     {@link String }
                 *     
                 */
                public void setSupportUID(String value) {
                    this.supportUID = value;
                }

            }

        }


        /**
         * <p>Java class for anonymous complex type.
         * 
         * <p>The following schema fragment specifies the expected content contained within this class.
         * 
         * <pre>
         * &lt;complexType>
         *   &lt;complexContent>
         *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
         *       &lt;sequence>
         *         &lt;element name="StatusCode" type="{http://www.w3.org/2001/XMLSchema}byte"/>
         *         &lt;element name="Severity" type="{http://www.w3.org/2001/XMLSchema}string"/>
         *         &lt;element name="StatusDesc" type="{http://www.w3.org/2001/XMLSchema}string"/>
         *         &lt;element name="SupportUID" type="{http://www.w3.org/2001/XMLSchema}string"/>
         *       &lt;/sequence>
         *     &lt;/restriction>
         *   &lt;/complexContent>
         * &lt;/complexType>
         * </pre>
         * 
         * 
         */
        @XmlAccessorType(XmlAccessType.FIELD)
        @XmlType(name = "", propOrder = {
            "statusCode",
            "severity",
            "statusDesc",
            "supportUID"
        })
        public static class Status {

            @XmlElement(name = "StatusCode")
            protected byte statusCode;
            @XmlElement(name = "Severity", required = true)
            protected String severity;
            @XmlElement(name = "StatusDesc", required = true)
            protected String statusDesc;
            @XmlElement(name = "SupportUID", required = true)
            protected String supportUID;

            /**
             * Gets the value of the statusCode property.
             * 
             */
            public byte getStatusCode() {
                return statusCode;
            }

            /**
             * Sets the value of the statusCode property.
             * 
             */
            public void setStatusCode(byte value) {
                this.statusCode = value;
            }

            /**
             * Gets the value of the severity property.
             * 
             * @return
             *     possible object is
             *     {@link String }
             *     
             */
            public String getSeverity() {
                return severity;
            }

            /**
             * Sets the value of the severity property.
             * 
             * @param value
             *     allowed object is
             *     {@link String }
             *     
             */
            public void setSeverity(String value) {
                this.severity = value;
            }

            /**
             * Gets the value of the statusDesc property.
             * 
             * @return
             *     possible object is
             *     {@link String }
             *     
             */
            public String getStatusDesc() {
                return statusDesc;
            }

            /**
             * Sets the value of the statusDesc property.
             * 
             * @param value
             *     allowed object is
             *     {@link String }
             *     
             */
            public void setStatusDesc(String value) {
                this.statusDesc = value;
            }

            /**
             * Gets the value of the supportUID property.
             * 
             * @return
             *     possible object is
             *     {@link String }
             *     
             */
            public String getSupportUID() {
                return supportUID;
            }

            /**
             * Sets the value of the supportUID property.
             * 
             * @param value
             *     allowed object is
             *     {@link String }
             *     
             */
            public void setSupportUID(String value) {
                this.supportUID = value;
            }

        }

    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType>
     *   &lt;complexContent>
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *       &lt;sequence>
     *         &lt;element name="Status">
     *           &lt;complexType>
     *             &lt;complexContent>
     *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *                 &lt;sequence>
     *                   &lt;element name="StatusCode" type="{http://www.w3.org/2001/XMLSchema}byte"/>
     *                   &lt;element name="Severity" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *                   &lt;element name="StatusDesc" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *                   &lt;element name="SupportUID" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *                 &lt;/sequence>
     *               &lt;/restriction>
     *             &lt;/complexContent>
     *           &lt;/complexType>
     *         &lt;/element>
     *         &lt;element name="SignonRole" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *         &lt;element name="CustId">
     *           &lt;complexType>
     *             &lt;complexContent>
     *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *                 &lt;sequence>
     *                   &lt;element name="SPName" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *                   &lt;element name="CustLoginId" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *                 &lt;/sequence>
     *               &lt;/restriction>
     *             &lt;/complexContent>
     *           &lt;/complexType>
     *         &lt;/element>
     *         &lt;element name="GenSessKey" type="{http://www.w3.org/2001/XMLSchema}byte"/>
     *         &lt;element name="ClientDt">
     *           &lt;complexType>
     *             &lt;complexContent>
     *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *                 &lt;sequence>
     *                   &lt;element name="Year" type="{http://www.w3.org/2001/XMLSchema}short"/>
     *                   &lt;element name="Month" type="{http://www.w3.org/2001/XMLSchema}byte"/>
     *                   &lt;element name="Day" type="{http://www.w3.org/2001/XMLSchema}byte"/>
     *                 &lt;/sequence>
     *               &lt;/restriction>
     *             &lt;/complexContent>
     *           &lt;/complexType>
     *         &lt;/element>
     *         &lt;element name="CustLangPref" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *         &lt;element name="ClientApp">
     *           &lt;complexType>
     *             &lt;complexContent>
     *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *                 &lt;sequence>
     *                   &lt;element name="Org" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *                   &lt;element name="Name" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *                   &lt;element name="Version" type="{http://www.w3.org/2001/XMLSchema}float"/>
     *                   &lt;element name="ClientAppKey" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *                 &lt;/sequence>
     *               &lt;/restriction>
     *             &lt;/complexContent>
     *           &lt;/complexType>
     *         &lt;/element>
     *         &lt;element name="ServerDt">
     *           &lt;complexType>
     *             &lt;complexContent>
     *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *                 &lt;sequence>
     *                   &lt;element name="Year" type="{http://www.w3.org/2001/XMLSchema}short"/>
     *                   &lt;element name="Month" type="{http://www.w3.org/2001/XMLSchema}byte"/>
     *                   &lt;element name="Day" type="{http://www.w3.org/2001/XMLSchema}byte"/>
     *                   &lt;element name="Hour" type="{http://www.w3.org/2001/XMLSchema}byte"/>
     *                   &lt;element name="Minute" type="{http://www.w3.org/2001/XMLSchema}byte"/>
     *                   &lt;element name="Second" type="{http://www.w3.org/2001/XMLSchema}byte"/>
     *                   &lt;element name="Fraction" type="{http://www.w3.org/2001/XMLSchema}int"/>
     *                   &lt;element name="UTCOffset" type="{http://www.w3.org/2001/XMLSchema}short"/>
     *                 &lt;/sequence>
     *               &lt;/restriction>
     *             &lt;/complexContent>
     *           &lt;/complexType>
     *         &lt;/element>
     *         &lt;element name="Language" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *         &lt;element name="ComputerKey" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *         &lt;element name="PersonName">
     *           &lt;complexType>
     *             &lt;complexContent>
     *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *                 &lt;sequence>
     *                   &lt;element name="LastName" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *                   &lt;element name="FirstName" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *                 &lt;/sequence>
     *               &lt;/restriction>
     *             &lt;/complexContent>
     *           &lt;/complexType>
     *         &lt;/element>
     *       &lt;/sequence>
     *     &lt;/restriction>
     *   &lt;/complexContent>
     * &lt;/complexType>
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "status",
        "signonRole",
        "custId",
        "genSessKey",
        "clientDt",
        "custLangPref",
        "clientApp",
        "serverDt",
        "language",
        "computerKey",
        "personName"
    })
    public static class SignonRs {

        @XmlElement(name = "Status", required = true)
        protected IFX.SignonRs.Status status;
        @XmlElement(name = "SignonRole", required = true)
        protected String signonRole;
        @XmlElement(name = "CustId", required = true)
        protected IFX.SignonRs.CustId custId;
        @XmlElement(name = "GenSessKey")
        protected byte genSessKey;
        @XmlElement(name = "ClientDt", required = true)
        protected IFX.SignonRs.ClientDt clientDt;
        @XmlElement(name = "CustLangPref", required = true)
        protected String custLangPref;
        @XmlElement(name = "ClientApp", required = true)
        protected IFX.SignonRs.ClientApp clientApp;
        @XmlElement(name = "ServerDt", required = true)
        protected IFX.SignonRs.ServerDt serverDt;
        @XmlElement(name = "Language", required = true)
        protected String language;
        @XmlElement(name = "ComputerKey", required = true)
        protected String computerKey;
        @XmlElement(name = "PersonName", required = true)
        protected IFX.SignonRs.PersonName personName;

        /**
         * Gets the value of the status property.
         * 
         * @return
         *     possible object is
         *     {@link IFX.SignonRs.Status }
         *     
         */
        public IFX.SignonRs.Status getStatus() {
            return status;
        }

        /**
         * Sets the value of the status property.
         * 
         * @param value
         *     allowed object is
         *     {@link IFX.SignonRs.Status }
         *     
         */
        public void setStatus(IFX.SignonRs.Status value) {
            this.status = value;
        }

        /**
         * Gets the value of the signonRole property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getSignonRole() {
            return signonRole;
        }

        /**
         * Sets the value of the signonRole property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setSignonRole(String value) {
            this.signonRole = value;
        }

        /**
         * Gets the value of the custId property.
         * 
         * @return
         *     possible object is
         *     {@link IFX.SignonRs.CustId }
         *     
         */
        public IFX.SignonRs.CustId getCustId() {
            return custId;
        }

        /**
         * Sets the value of the custId property.
         * 
         * @param value
         *     allowed object is
         *     {@link IFX.SignonRs.CustId }
         *     
         */
        public void setCustId(IFX.SignonRs.CustId value) {
            this.custId = value;
        }

        /**
         * Gets the value of the genSessKey property.
         * 
         */
        public byte getGenSessKey() {
            return genSessKey;
        }

        /**
         * Sets the value of the genSessKey property.
         * 
         */
        public void setGenSessKey(byte value) {
            this.genSessKey = value;
        }

        /**
         * Gets the value of the clientDt property.
         * 
         * @return
         *     possible object is
         *     {@link IFX.SignonRs.ClientDt }
         *     
         */
        public IFX.SignonRs.ClientDt getClientDt() {
            return clientDt;
        }

        /**
         * Sets the value of the clientDt property.
         * 
         * @param value
         *     allowed object is
         *     {@link IFX.SignonRs.ClientDt }
         *     
         */
        public void setClientDt(IFX.SignonRs.ClientDt value) {
            this.clientDt = value;
        }

        /**
         * Gets the value of the custLangPref property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getCustLangPref() {
            return custLangPref;
        }

        /**
         * Sets the value of the custLangPref property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setCustLangPref(String value) {
            this.custLangPref = value;
        }

        /**
         * Gets the value of the clientApp property.
         * 
         * @return
         *     possible object is
         *     {@link IFX.SignonRs.ClientApp }
         *     
         */
        public IFX.SignonRs.ClientApp getClientApp() {
            return clientApp;
        }

        /**
         * Sets the value of the clientApp property.
         * 
         * @param value
         *     allowed object is
         *     {@link IFX.SignonRs.ClientApp }
         *     
         */
        public void setClientApp(IFX.SignonRs.ClientApp value) {
            this.clientApp = value;
        }

        /**
         * Gets the value of the serverDt property.
         * 
         * @return
         *     possible object is
         *     {@link IFX.SignonRs.ServerDt }
         *     
         */
        public IFX.SignonRs.ServerDt getServerDt() {
            return serverDt;
        }

        /**
         * Sets the value of the serverDt property.
         * 
         * @param value
         *     allowed object is
         *     {@link IFX.SignonRs.ServerDt }
         *     
         */
        public void setServerDt(IFX.SignonRs.ServerDt value) {
            this.serverDt = value;
        }

        /**
         * Gets the value of the language property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getLanguage() {
            return language;
        }

        /**
         * Sets the value of the language property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setLanguage(String value) {
            this.language = value;
        }

        /**
         * Gets the value of the computerKey property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getComputerKey() {
            return computerKey;
        }

        /**
         * Sets the value of the computerKey property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setComputerKey(String value) {
            this.computerKey = value;
        }

        /**
         * Gets the value of the personName property.
         * 
         * @return
         *     possible object is
         *     {@link IFX.SignonRs.PersonName }
         *     
         */
        public IFX.SignonRs.PersonName getPersonName() {
            return personName;
        }

        /**
         * Sets the value of the personName property.
         * 
         * @param value
         *     allowed object is
         *     {@link IFX.SignonRs.PersonName }
         *     
         */
        public void setPersonName(IFX.SignonRs.PersonName value) {
            this.personName = value;
        }


        /**
         * <p>Java class for anonymous complex type.
         * 
         * <p>The following schema fragment specifies the expected content contained within this class.
         * 
         * <pre>
         * &lt;complexType>
         *   &lt;complexContent>
         *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
         *       &lt;sequence>
         *         &lt;element name="Org" type="{http://www.w3.org/2001/XMLSchema}string"/>
         *         &lt;element name="Name" type="{http://www.w3.org/2001/XMLSchema}string"/>
         *         &lt;element name="Version" type="{http://www.w3.org/2001/XMLSchema}float"/>
         *         &lt;element name="ClientAppKey" type="{http://www.w3.org/2001/XMLSchema}string"/>
         *       &lt;/sequence>
         *     &lt;/restriction>
         *   &lt;/complexContent>
         * &lt;/complexType>
         * </pre>
         * 
         * 
         */
        @XmlAccessorType(XmlAccessType.FIELD)
        @XmlType(name = "", propOrder = {
            "org",
            "name",
            "version",
            "clientAppKey"
        })
        public static class ClientApp {

            @XmlElement(name = "Org", required = true)
            protected String org;
            @XmlElement(name = "Name", required = true)
            protected String name;
            @XmlElement(name = "Version")
            protected float version;
            @XmlElement(name = "ClientAppKey", required = true)
            protected String clientAppKey;

            /**
             * Gets the value of the org property.
             * 
             * @return
             *     possible object is
             *     {@link String }
             *     
             */
            public String getOrg() {
                return org;
            }

            /**
             * Sets the value of the org property.
             * 
             * @param value
             *     allowed object is
             *     {@link String }
             *     
             */
            public void setOrg(String value) {
                this.org = value;
            }

            /**
             * Gets the value of the name property.
             * 
             * @return
             *     possible object is
             *     {@link String }
             *     
             */
            public String getName() {
                return name;
            }

            /**
             * Sets the value of the name property.
             * 
             * @param value
             *     allowed object is
             *     {@link String }
             *     
             */
            public void setName(String value) {
                this.name = value;
            }

            /**
             * Gets the value of the version property.
             * 
             */
            public float getVersion() {
                return version;
            }

            /**
             * Sets the value of the version property.
             * 
             */
            public void setVersion(float value) {
                this.version = value;
            }

            /**
             * Gets the value of the clientAppKey property.
             * 
             * @return
             *     possible object is
             *     {@link String }
             *     
             */
            public String getClientAppKey() {
                return clientAppKey;
            }

            /**
             * Sets the value of the clientAppKey property.
             * 
             * @param value
             *     allowed object is
             *     {@link String }
             *     
             */
            public void setClientAppKey(String value) {
                this.clientAppKey = value;
            }

        }


        /**
         * <p>Java class for anonymous complex type.
         * 
         * <p>The following schema fragment specifies the expected content contained within this class.
         * 
         * <pre>
         * &lt;complexType>
         *   &lt;complexContent>
         *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
         *       &lt;sequence>
         *         &lt;element name="Year" type="{http://www.w3.org/2001/XMLSchema}short"/>
         *         &lt;element name="Month" type="{http://www.w3.org/2001/XMLSchema}byte"/>
         *         &lt;element name="Day" type="{http://www.w3.org/2001/XMLSchema}byte"/>
         *       &lt;/sequence>
         *     &lt;/restriction>
         *   &lt;/complexContent>
         * &lt;/complexType>
         * </pre>
         * 
         * 
         */
        @XmlAccessorType(XmlAccessType.FIELD)
        @XmlType(name = "", propOrder = {
            "year",
            "month",
            "day"
        })
        public static class ClientDt {

            @XmlElement(name = "Year")
            protected short year;
            @XmlElement(name = "Month")
            protected byte month;
            @XmlElement(name = "Day")
            protected byte day;

            /**
             * Gets the value of the year property.
             * 
             */
            public short getYear() {
                return year;
            }

            /**
             * Sets the value of the year property.
             * 
             */
            public void setYear(short value) {
                this.year = value;
            }

            /**
             * Gets the value of the month property.
             * 
             */
            public byte getMonth() {
                return month;
            }

            /**
             * Sets the value of the month property.
             * 
             */
            public void setMonth(byte value) {
                this.month = value;
            }

            /**
             * Gets the value of the day property.
             * 
             */
            public byte getDay() {
                return day;
            }

            /**
             * Sets the value of the day property.
             * 
             */
            public void setDay(byte value) {
                this.day = value;
            }

        }


        /**
         * <p>Java class for anonymous complex type.
         * 
         * <p>The following schema fragment specifies the expected content contained within this class.
         * 
         * <pre>
         * &lt;complexType>
         *   &lt;complexContent>
         *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
         *       &lt;sequence>
         *         &lt;element name="SPName" type="{http://www.w3.org/2001/XMLSchema}string"/>
         *         &lt;element name="CustLoginId" type="{http://www.w3.org/2001/XMLSchema}string"/>
         *       &lt;/sequence>
         *     &lt;/restriction>
         *   &lt;/complexContent>
         * &lt;/complexType>
         * </pre>
         * 
         * 
         */
        @XmlAccessorType(XmlAccessType.FIELD)
        @XmlType(name = "", propOrder = {
            "spName",
            "custLoginId"
        })
        public static class CustId {

            @XmlElement(name = "SPName", required = true)
            protected String spName;
            @XmlElement(name = "CustLoginId", required = true)
            protected String custLoginId;

            /**
             * Gets the value of the spName property.
             * 
             * @return
             *     possible object is
             *     {@link String }
             *     
             */
            public String getSPName() {
                return spName;
            }

            /**
             * Sets the value of the spName property.
             * 
             * @param value
             *     allowed object is
             *     {@link String }
             *     
             */
            public void setSPName(String value) {
                this.spName = value;
            }

            /**
             * Gets the value of the custLoginId property.
             * 
             * @return
             *     possible object is
             *     {@link String }
             *     
             */
            public String getCustLoginId() {
                return custLoginId;
            }

            /**
             * Sets the value of the custLoginId property.
             * 
             * @param value
             *     allowed object is
             *     {@link String }
             *     
             */
            public void setCustLoginId(String value) {
                this.custLoginId = value;
            }

        }


        /**
         * <p>Java class for anonymous complex type.
         * 
         * <p>The following schema fragment specifies the expected content contained within this class.
         * 
         * <pre>
         * &lt;complexType>
         *   &lt;complexContent>
         *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
         *       &lt;sequence>
         *         &lt;element name="LastName" type="{http://www.w3.org/2001/XMLSchema}string"/>
         *         &lt;element name="FirstName" type="{http://www.w3.org/2001/XMLSchema}string"/>
         *       &lt;/sequence>
         *     &lt;/restriction>
         *   &lt;/complexContent>
         * &lt;/complexType>
         * </pre>
         * 
         * 
         */
        @XmlAccessorType(XmlAccessType.FIELD)
        @XmlType(name = "", propOrder = {
            "lastName",
            "firstName"
        })
        public static class PersonName {

            @XmlElement(name = "LastName", required = true)
            protected String lastName;
            @XmlElement(name = "FirstName", required = true)
            protected String firstName;

            /**
             * Gets the value of the lastName property.
             * 
             * @return
             *     possible object is
             *     {@link String }
             *     
             */
            public String getLastName() {
                return lastName;
            }

            /**
             * Sets the value of the lastName property.
             * 
             * @param value
             *     allowed object is
             *     {@link String }
             *     
             */
            public void setLastName(String value) {
                this.lastName = value;
            }

            /**
             * Gets the value of the firstName property.
             * 
             * @return
             *     possible object is
             *     {@link String }
             *     
             */
            public String getFirstName() {
                return firstName;
            }

            /**
             * Sets the value of the firstName property.
             * 
             * @param value
             *     allowed object is
             *     {@link String }
             *     
             */
            public void setFirstName(String value) {
                this.firstName = value;
            }

        }


        /**
         * <p>Java class for anonymous complex type.
         * 
         * <p>The following schema fragment specifies the expected content contained within this class.
         * 
         * <pre>
         * &lt;complexType>
         *   &lt;complexContent>
         *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
         *       &lt;sequence>
         *         &lt;element name="Year" type="{http://www.w3.org/2001/XMLSchema}short"/>
         *         &lt;element name="Month" type="{http://www.w3.org/2001/XMLSchema}byte"/>
         *         &lt;element name="Day" type="{http://www.w3.org/2001/XMLSchema}byte"/>
         *         &lt;element name="Hour" type="{http://www.w3.org/2001/XMLSchema}byte"/>
         *         &lt;element name="Minute" type="{http://www.w3.org/2001/XMLSchema}byte"/>
         *         &lt;element name="Second" type="{http://www.w3.org/2001/XMLSchema}byte"/>
         *         &lt;element name="Fraction" type="{http://www.w3.org/2001/XMLSchema}int"/>
         *         &lt;element name="UTCOffset" type="{http://www.w3.org/2001/XMLSchema}short"/>
         *       &lt;/sequence>
         *     &lt;/restriction>
         *   &lt;/complexContent>
         * &lt;/complexType>
         * </pre>
         * 
         * 
         */
        @XmlAccessorType(XmlAccessType.FIELD)
        @XmlType(name = "", propOrder = {
            "year",
            "month",
            "day",
            "hour",
            "minute",
            "second",
            "fraction",
            "utcOffset"
        })
        public static class ServerDt {

            @XmlElement(name = "Year")
            protected short year;
            @XmlElement(name = "Month")
            protected byte month;
            @XmlElement(name = "Day")
            protected byte day;
            @XmlElement(name = "Hour")
            protected byte hour;
            @XmlElement(name = "Minute")
            protected byte minute;
            @XmlElement(name = "Second")
            protected byte second;
            @XmlElement(name = "Fraction")
            protected int fraction;
            @XmlElement(name = "UTCOffset")
            protected short utcOffset;

            /**
             * Gets the value of the year property.
             * 
             */
            public short getYear() {
                return year;
            }

            /**
             * Sets the value of the year property.
             * 
             */
            public void setYear(short value) {
                this.year = value;
            }

            /**
             * Gets the value of the month property.
             * 
             */
            public byte getMonth() {
                return month;
            }

            /**
             * Sets the value of the month property.
             * 
             */
            public void setMonth(byte value) {
                this.month = value;
            }

            /**
             * Gets the value of the day property.
             * 
             */
            public byte getDay() {
                return day;
            }

            /**
             * Sets the value of the day property.
             * 
             */
            public void setDay(byte value) {
                this.day = value;
            }

            /**
             * Gets the value of the hour property.
             * 
             */
            public byte getHour() {
                return hour;
            }

            /**
             * Sets the value of the hour property.
             * 
             */
            public void setHour(byte value) {
                this.hour = value;
            }

            /**
             * Gets the value of the minute property.
             * 
             */
            public byte getMinute() {
                return minute;
            }

            /**
             * Sets the value of the minute property.
             * 
             */
            public void setMinute(byte value) {
                this.minute = value;
            }

            /**
             * Gets the value of the second property.
             * 
             */
            public byte getSecond() {
                return second;
            }

            /**
             * Sets the value of the second property.
             * 
             */
            public void setSecond(byte value) {
                this.second = value;
            }

            /**
             * Gets the value of the fraction property.
             * 
             */
            public int getFraction() {
                return fraction;
            }

            /**
             * Sets the value of the fraction property.
             * 
             */
            public void setFraction(int value) {
                this.fraction = value;
            }

            /**
             * Gets the value of the utcOffset property.
             * 
             */
            public short getUTCOffset() {
                return utcOffset;
            }

            /**
             * Sets the value of the utcOffset property.
             * 
             */
            public void setUTCOffset(short value) {
                this.utcOffset = value;
            }

        }


        /**
         * <p>Java class for anonymous complex type.
         * 
         * <p>The following schema fragment specifies the expected content contained within this class.
         * 
         * <pre>
         * &lt;complexType>
         *   &lt;complexContent>
         *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
         *       &lt;sequence>
         *         &lt;element name="StatusCode" type="{http://www.w3.org/2001/XMLSchema}byte"/>
         *         &lt;element name="Severity" type="{http://www.w3.org/2001/XMLSchema}string"/>
         *         &lt;element name="StatusDesc" type="{http://www.w3.org/2001/XMLSchema}string"/>
         *         &lt;element name="SupportUID" type="{http://www.w3.org/2001/XMLSchema}string"/>
         *       &lt;/sequence>
         *     &lt;/restriction>
         *   &lt;/complexContent>
         * &lt;/complexType>
         * </pre>
         * 
         * 
         */
        @XmlAccessorType(XmlAccessType.FIELD)
        @XmlType(name = "", propOrder = {
            "statusCode",
            "severity",
            "statusDesc",
            "supportUID"
        })
        public static class Status {

            @XmlElement(name = "StatusCode")
            protected byte statusCode;
            @XmlElement(name = "Severity", required = true)
            protected String severity;
            @XmlElement(name = "StatusDesc", required = true)
            protected String statusDesc;
            @XmlElement(name = "SupportUID", required = true)
            protected String supportUID;

            /**
             * Gets the value of the statusCode property.
             * 
             */
            public byte getStatusCode() {
                return statusCode;
            }

            /**
             * Sets the value of the statusCode property.
             * 
             */
            public void setStatusCode(byte value) {
                this.statusCode = value;
            }

            /**
             * Gets the value of the severity property.
             * 
             * @return
             *     possible object is
             *     {@link String }
             *     
             */
            public String getSeverity() {
                return severity;
            }

            /**
             * Sets the value of the severity property.
             * 
             * @param value
             *     allowed object is
             *     {@link String }
             *     
             */
            public void setSeverity(String value) {
                this.severity = value;
            }

            /**
             * Gets the value of the statusDesc property.
             * 
             * @return
             *     possible object is
             *     {@link String }
             *     
             */
            public String getStatusDesc() {
                return statusDesc;
            }

            /**
             * Sets the value of the statusDesc property.
             * 
             * @param value
             *     allowed object is
             *     {@link String }
             *     
             */
            public void setStatusDesc(String value) {
                this.statusDesc = value;
            }

            /**
             * Gets the value of the supportUID property.
             * 
             * @return
             *     possible object is
             *     {@link String }
             *     
             */
            public String getSupportUID() {
                return supportUID;
            }

            /**
             * Sets the value of the supportUID property.
             * 
             * @param value
             *     allowed object is
             *     {@link String }
             *     
             */
            public void setSupportUID(String value) {
                this.supportUID = value;
            }

        }

    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType>
     *   &lt;complexContent>
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *       &lt;sequence>
     *         &lt;element name="StatusCode" type="{http://www.w3.org/2001/XMLSchema}byte"/>
     *         &lt;element name="Severity" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *         &lt;element name="StatusDesc" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *         &lt;element name="SupportUID" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *       &lt;/sequence>
     *     &lt;/restriction>
     *   &lt;/complexContent>
     * &lt;/complexType>
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "statusCode",
        "severity",
        "statusDesc",
        "supportUID"
    })
    public static class Status {

        @XmlElement(name = "StatusCode")
        protected byte statusCode;
        @XmlElement(name = "Severity", required = true)
        protected String severity;
        @XmlElement(name = "StatusDesc", required = true)
        protected String statusDesc;
        @XmlElement(name = "SupportUID", required = true)
        protected String supportUID;

        /**
         * Gets the value of the statusCode property.
         * 
         */
        public byte getStatusCode() {
            return statusCode;
        }

        /**
         * Sets the value of the statusCode property.
         * 
         */
        public void setStatusCode(byte value) {
            this.statusCode = value;
        }

        /**
         * Gets the value of the severity property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getSeverity() {
            return severity;
        }

        /**
         * Sets the value of the severity property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setSeverity(String value) {
            this.severity = value;
        }

        /**
         * Gets the value of the statusDesc property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getStatusDesc() {
            return statusDesc;
        }

        /**
         * Sets the value of the statusDesc property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setStatusDesc(String value) {
            this.statusDesc = value;
        }

        /**
         * Gets the value of the supportUID property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getSupportUID() {
            return supportUID;
        }

        /**
         * Sets the value of the supportUID property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setSupportUID(String value) {
            this.supportUID = value;
        }

    }

}
