//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2020.03.18 at 04:23:53 PM IST 
//


package com.boc.accountcustomerrequest;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="SignonRq">
 *           &lt;complexType>
 *             &lt;complexContent>
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                 &lt;sequence>
 *                   &lt;element name="SignonPswd">
 *                     &lt;complexType>
 *                       &lt;complexContent>
 *                         &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                           &lt;sequence>
 *                             &lt;element name="SignonRole" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                             &lt;element name="CustId">
 *                               &lt;complexType>
 *                                 &lt;complexContent>
 *                                   &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                                     &lt;sequence>
 *                                       &lt;element name="SPName" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                                       &lt;element name="CustLoginId" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                                     &lt;/sequence>
 *                                   &lt;/restriction>
 *                                 &lt;/complexContent>
 *                               &lt;/complexType>
 *                             &lt;/element>
 *                             &lt;element name="CustPswd">
 *                               &lt;complexType>
 *                                 &lt;complexContent>
 *                                   &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                                     &lt;sequence>
 *                                       &lt;element name="CryptType" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                                       &lt;element name="Pswd" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                                     &lt;/sequence>
 *                                   &lt;/restriction>
 *                                 &lt;/complexContent>
 *                               &lt;/complexType>
 *                             &lt;/element>
 *                             &lt;element name="GenSessKey" type="{http://www.w3.org/2001/XMLSchema}byte"/>
 *                           &lt;/sequence>
 *                         &lt;/restriction>
 *                       &lt;/complexContent>
 *                     &lt;/complexType>
 *                   &lt;/element>
 *                   &lt;element name="ClientDt">
 *                     &lt;complexType>
 *                       &lt;complexContent>
 *                         &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                           &lt;sequence>
 *                             &lt;element name="Year" type="{http://www.w3.org/2001/XMLSchema}short"/>
 *                             &lt;element name="Month" type="{http://www.w3.org/2001/XMLSchema}byte"/>
 *                             &lt;element name="Day" type="{http://www.w3.org/2001/XMLSchema}byte"/>
 *                           &lt;/sequence>
 *                         &lt;/restriction>
 *                       &lt;/complexContent>
 *                     &lt;/complexType>
 *                   &lt;/element>
 *                   &lt;element name="ClientApp">
 *                     &lt;complexType>
 *                       &lt;complexContent>
 *                         &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                           &lt;sequence>
 *                             &lt;element name="Org" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                             &lt;element name="Name" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                             &lt;element name="Version" type="{http://www.w3.org/2001/XMLSchema}float"/>
 *                             &lt;element name="ClientAppKey" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                           &lt;/sequence>
 *                         &lt;/restriction>
 *                       &lt;/complexContent>
 *                     &lt;/complexType>
 *                   &lt;/element>
 *                   &lt;element name="ComputerId" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                   &lt;element name="InstitutionCode" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                 &lt;/sequence>
 *               &lt;/restriction>
 *             &lt;/complexContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *         &lt;element name="EnvironmentInfo">
 *           &lt;complexType>
 *             &lt;complexContent>
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                 &lt;sequence>
 *                   &lt;element name="EnvironmentName" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                 &lt;/sequence>
 *               &lt;/restriction>
 *             &lt;/complexContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *         &lt;element name="MaintSvcRq">
 *           &lt;complexType>
 *             &lt;complexContent>
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                 &lt;sequence>
 *                   &lt;element name="RqUID" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                   &lt;element name="SPName" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                   &lt;element name="AcctCustInqRq">
 *                     &lt;complexType>
 *                       &lt;complexContent>
 *                         &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                           &lt;sequence>
 *                             &lt;element name="RqUID" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                             &lt;element name="SPName" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                             &lt;element name="BankAcctId">
 *                               &lt;complexType>
 *                                 &lt;complexContent>
 *                                   &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                                     &lt;sequence>
 *                                       &lt;element name="AcctType" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                                       &lt;element name="AcctId" type="{http://www.w3.org/2001/XMLSchema}int"/>
 *                                     &lt;/sequence>
 *                                   &lt;/restriction>
 *                                 &lt;/complexContent>
 *                               &lt;/complexType>
 *                             &lt;/element>
 *                           &lt;/sequence>
 *                         &lt;/restriction>
 *                       &lt;/complexContent>
 *                     &lt;/complexType>
 *                   &lt;/element>
 *                 &lt;/sequence>
 *               &lt;/restriction>
 *             &lt;/complexContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "signonRq",
    "environmentInfo",
    "maintSvcRq"
})
@XmlRootElement(name = "IFX")
public class IFX {

    @XmlElement(name = "SignonRq", required = true)
    protected IFX.SignonRq signonRq;
    @XmlElement(name = "EnvironmentInfo", required = true)
    protected IFX.EnvironmentInfo environmentInfo;
    @XmlElement(name = "MaintSvcRq", required = true)
    protected IFX.MaintSvcRq maintSvcRq;

    /**
     * Gets the value of the signonRq property.
     * 
     * @return
     *     possible object is
     *     {@link IFX.SignonRq }
     *     
     */
    public IFX.SignonRq getSignonRq() {
        return signonRq;
    }

    /**
     * Sets the value of the signonRq property.
     * 
     * @param value
     *     allowed object is
     *     {@link IFX.SignonRq }
     *     
     */
    public void setSignonRq(IFX.SignonRq value) {
        this.signonRq = value;
    }

    /**
     * Gets the value of the environmentInfo property.
     * 
     * @return
     *     possible object is
     *     {@link IFX.EnvironmentInfo }
     *     
     */
    public IFX.EnvironmentInfo getEnvironmentInfo() {
        return environmentInfo;
    }

    /**
     * Sets the value of the environmentInfo property.
     * 
     * @param value
     *     allowed object is
     *     {@link IFX.EnvironmentInfo }
     *     
     */
    public void setEnvironmentInfo(IFX.EnvironmentInfo value) {
        this.environmentInfo = value;
    }

    /**
     * Gets the value of the maintSvcRq property.
     * 
     * @return
     *     possible object is
     *     {@link IFX.MaintSvcRq }
     *     
     */
    public IFX.MaintSvcRq getMaintSvcRq() {
        return maintSvcRq;
    }

    /**
     * Sets the value of the maintSvcRq property.
     * 
     * @param value
     *     allowed object is
     *     {@link IFX.MaintSvcRq }
     *     
     */
    public void setMaintSvcRq(IFX.MaintSvcRq value) {
        this.maintSvcRq = value;
    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType>
     *   &lt;complexContent>
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *       &lt;sequence>
     *         &lt;element name="EnvironmentName" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *       &lt;/sequence>
     *     &lt;/restriction>
     *   &lt;/complexContent>
     * &lt;/complexType>
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "environmentName"
    })
    public static class EnvironmentInfo {

        @XmlElement(name = "EnvironmentName", required = true)
        protected String environmentName;

        /**
         * Gets the value of the environmentName property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getEnvironmentName() {
            return environmentName;
        }

        /**
         * Sets the value of the environmentName property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setEnvironmentName(String value) {
            this.environmentName = value;
        }

    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType>
     *   &lt;complexContent>
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *       &lt;sequence>
     *         &lt;element name="RqUID" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *         &lt;element name="SPName" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *         &lt;element name="AcctCustInqRq">
     *           &lt;complexType>
     *             &lt;complexContent>
     *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *                 &lt;sequence>
     *                   &lt;element name="RqUID" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *                   &lt;element name="SPName" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *                   &lt;element name="BankAcctId">
     *                     &lt;complexType>
     *                       &lt;complexContent>
     *                         &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *                           &lt;sequence>
     *                             &lt;element name="AcctType" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *                             &lt;element name="AcctId" type="{http://www.w3.org/2001/XMLSchema}int"/>
     *                           &lt;/sequence>
     *                         &lt;/restriction>
     *                       &lt;/complexContent>
     *                     &lt;/complexType>
     *                   &lt;/element>
     *                 &lt;/sequence>
     *               &lt;/restriction>
     *             &lt;/complexContent>
     *           &lt;/complexType>
     *         &lt;/element>
     *       &lt;/sequence>
     *     &lt;/restriction>
     *   &lt;/complexContent>
     * &lt;/complexType>
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "rqUID",
        "spName",
        "acctCustInqRq"
    })
    public static class MaintSvcRq {

        @XmlElement(name = "RqUID", required = true)
        protected String rqUID;
        @XmlElement(name = "SPName", required = true)
        protected String spName;
        @XmlElement(name = "AcctCustInqRq", required = true)
        protected IFX.MaintSvcRq.AcctCustInqRq acctCustInqRq;

        /**
         * Gets the value of the rqUID property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getRqUID() {
            return rqUID;
        }

        /**
         * Sets the value of the rqUID property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setRqUID(String value) {
            this.rqUID = value;
        }

        /**
         * Gets the value of the spName property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getSPName() {
            return spName;
        }

        /**
         * Sets the value of the spName property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setSPName(String value) {
            this.spName = value;
        }

        /**
         * Gets the value of the acctCustInqRq property.
         * 
         * @return
         *     possible object is
         *     {@link IFX.MaintSvcRq.AcctCustInqRq }
         *     
         */
        public IFX.MaintSvcRq.AcctCustInqRq getAcctCustInqRq() {
            return acctCustInqRq;
        }

        /**
         * Sets the value of the acctCustInqRq property.
         * 
         * @param value
         *     allowed object is
         *     {@link IFX.MaintSvcRq.AcctCustInqRq }
         *     
         */
        public void setAcctCustInqRq(IFX.MaintSvcRq.AcctCustInqRq value) {
            this.acctCustInqRq = value;
        }


        /**
         * <p>Java class for anonymous complex type.
         * 
         * <p>The following schema fragment specifies the expected content contained within this class.
         * 
         * <pre>
         * &lt;complexType>
         *   &lt;complexContent>
         *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
         *       &lt;sequence>
         *         &lt;element name="RqUID" type="{http://www.w3.org/2001/XMLSchema}string"/>
         *         &lt;element name="SPName" type="{http://www.w3.org/2001/XMLSchema}string"/>
         *         &lt;element name="BankAcctId">
         *           &lt;complexType>
         *             &lt;complexContent>
         *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
         *                 &lt;sequence>
         *                   &lt;element name="AcctType" type="{http://www.w3.org/2001/XMLSchema}string"/>
         *                   &lt;element name="AcctId" type="{http://www.w3.org/2001/XMLSchema}int"/>
         *                 &lt;/sequence>
         *               &lt;/restriction>
         *             &lt;/complexContent>
         *           &lt;/complexType>
         *         &lt;/element>
         *       &lt;/sequence>
         *     &lt;/restriction>
         *   &lt;/complexContent>
         * &lt;/complexType>
         * </pre>
         * 
         * 
         */
        @XmlAccessorType(XmlAccessType.FIELD)
        @XmlType(name = "", propOrder = {
            "rqUID",
            "spName",
            "bankAcctId"
        })
        public static class AcctCustInqRq {

            @XmlElement(name = "RqUID", required = true)
            protected String rqUID;
            @XmlElement(name = "SPName", required = true)
            protected String spName;
            @XmlElement(name = "BankAcctId", required = true)
            protected IFX.MaintSvcRq.AcctCustInqRq.BankAcctId bankAcctId;

            /**
             * Gets the value of the rqUID property.
             * 
             * @return
             *     possible object is
             *     {@link String }
             *     
             */
            public String getRqUID() {
                return rqUID;
            }

            /**
             * Sets the value of the rqUID property.
             * 
             * @param value
             *     allowed object is
             *     {@link String }
             *     
             */
            public void setRqUID(String value) {
                this.rqUID = value;
            }

            /**
             * Gets the value of the spName property.
             * 
             * @return
             *     possible object is
             *     {@link String }
             *     
             */
            public String getSPName() {
                return spName;
            }

            /**
             * Sets the value of the spName property.
             * 
             * @param value
             *     allowed object is
             *     {@link String }
             *     
             */
            public void setSPName(String value) {
                this.spName = value;
            }

            /**
             * Gets the value of the bankAcctId property.
             * 
             * @return
             *     possible object is
             *     {@link IFX.MaintSvcRq.AcctCustInqRq.BankAcctId }
             *     
             */
            public IFX.MaintSvcRq.AcctCustInqRq.BankAcctId getBankAcctId() {
                return bankAcctId;
            }

            /**
             * Sets the value of the bankAcctId property.
             * 
             * @param value
             *     allowed object is
             *     {@link IFX.MaintSvcRq.AcctCustInqRq.BankAcctId }
             *     
             */
            public void setBankAcctId(IFX.MaintSvcRq.AcctCustInqRq.BankAcctId value) {
                this.bankAcctId = value;
            }


            /**
             * <p>Java class for anonymous complex type.
             * 
             * <p>The following schema fragment specifies the expected content contained within this class.
             * 
             * <pre>
             * &lt;complexType>
             *   &lt;complexContent>
             *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
             *       &lt;sequence>
             *         &lt;element name="AcctType" type="{http://www.w3.org/2001/XMLSchema}string"/>
             *         &lt;element name="AcctId" type="{http://www.w3.org/2001/XMLSchema}int"/>
             *       &lt;/sequence>
             *     &lt;/restriction>
             *   &lt;/complexContent>
             * &lt;/complexType>
             * </pre>
             * 
             * 
             */
            @XmlAccessorType(XmlAccessType.FIELD)
            @XmlType(name = "", propOrder = {
                "acctType",
                "acctId"
            })
            public static class BankAcctId {

                @XmlElement(name = "AcctType", required = true)
                protected String acctType;
                @XmlElement(name = "AcctId")
                protected String acctId;

                /**
                 * Gets the value of the acctType property.
                 * 
                 * @return
                 *     possible object is
                 *     {@link String }
                 *     
                 */
                public String getAcctType() {
                    return acctType;
                }

                /**
                 * Sets the value of the acctType property.
                 * 
                 * @param value
                 *     allowed object is
                 *     {@link String }
                 *     
                 */
                public void setAcctType(String value) {
                    this.acctType = value;
                }

                /**
                 * Gets the value of the acctId property.
                 * 
                 */
                public String getAcctId() {
                    return acctId;
                }

                /**
                 * Sets the value of the acctId property.
                 * 
                 */
                public void setAcctId(String value) {
                    this.acctId = value;
                }

            }

        }

    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType>
     *   &lt;complexContent>
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *       &lt;sequence>
     *         &lt;element name="SignonPswd">
     *           &lt;complexType>
     *             &lt;complexContent>
     *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *                 &lt;sequence>
     *                   &lt;element name="SignonRole" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *                   &lt;element name="CustId">
     *                     &lt;complexType>
     *                       &lt;complexContent>
     *                         &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *                           &lt;sequence>
     *                             &lt;element name="SPName" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *                             &lt;element name="CustLoginId" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *                           &lt;/sequence>
     *                         &lt;/restriction>
     *                       &lt;/complexContent>
     *                     &lt;/complexType>
     *                   &lt;/element>
     *                   &lt;element name="CustPswd">
     *                     &lt;complexType>
     *                       &lt;complexContent>
     *                         &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *                           &lt;sequence>
     *                             &lt;element name="CryptType" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *                             &lt;element name="Pswd" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *                           &lt;/sequence>
     *                         &lt;/restriction>
     *                       &lt;/complexContent>
     *                     &lt;/complexType>
     *                   &lt;/element>
     *                   &lt;element name="GenSessKey" type="{http://www.w3.org/2001/XMLSchema}byte"/>
     *                 &lt;/sequence>
     *               &lt;/restriction>
     *             &lt;/complexContent>
     *           &lt;/complexType>
     *         &lt;/element>
     *         &lt;element name="ClientDt">
     *           &lt;complexType>
     *             &lt;complexContent>
     *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *                 &lt;sequence>
     *                   &lt;element name="Year" type="{http://www.w3.org/2001/XMLSchema}short"/>
     *                   &lt;element name="Month" type="{http://www.w3.org/2001/XMLSchema}byte"/>
     *                   &lt;element name="Day" type="{http://www.w3.org/2001/XMLSchema}byte"/>
     *                 &lt;/sequence>
     *               &lt;/restriction>
     *             &lt;/complexContent>
     *           &lt;/complexType>
     *         &lt;/element>
     *         &lt;element name="ClientApp">
     *           &lt;complexType>
     *             &lt;complexContent>
     *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *                 &lt;sequence>
     *                   &lt;element name="Org" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *                   &lt;element name="Name" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *                   &lt;element name="Version" type="{http://www.w3.org/2001/XMLSchema}float"/>
     *                   &lt;element name="ClientAppKey" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *                 &lt;/sequence>
     *               &lt;/restriction>
     *             &lt;/complexContent>
     *           &lt;/complexType>
     *         &lt;/element>
     *         &lt;element name="ComputerId" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *         &lt;element name="InstitutionCode" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *       &lt;/sequence>
     *     &lt;/restriction>
     *   &lt;/complexContent>
     * &lt;/complexType>
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "signonPswd",
        "clientDt",
        "clientApp",
        "computerId",
        "institutionCode"
    })
    public static class SignonRq {

        @XmlElement(name = "SignonPswd", required = true)
        protected IFX.SignonRq.SignonPswd signonPswd;
        @XmlElement(name = "ClientDt", required = true)
        protected IFX.SignonRq.ClientDt clientDt;
        @XmlElement(name = "ClientApp", required = true)
        protected IFX.SignonRq.ClientApp clientApp;
        @XmlElement(name = "ComputerId", required = true)
        protected String computerId;
        @XmlElement(name = "InstitutionCode", required = true)
        protected String institutionCode;

        /**
         * Gets the value of the signonPswd property.
         * 
         * @return
         *     possible object is
         *     {@link IFX.SignonRq.SignonPswd }
         *     
         */
        public IFX.SignonRq.SignonPswd getSignonPswd() {
            return signonPswd;
        }

        /**
         * Sets the value of the signonPswd property.
         * 
         * @param value
         *     allowed object is
         *     {@link IFX.SignonRq.SignonPswd }
         *     
         */
        public void setSignonPswd(IFX.SignonRq.SignonPswd value) {
            this.signonPswd = value;
        }

        /**
         * Gets the value of the clientDt property.
         * 
         * @return
         *     possible object is
         *     {@link IFX.SignonRq.ClientDt }
         *     
         */
        public IFX.SignonRq.ClientDt getClientDt() {
            return clientDt;
        }

        /**
         * Sets the value of the clientDt property.
         * 
         * @param value
         *     allowed object is
         *     {@link IFX.SignonRq.ClientDt }
         *     
         */
        public void setClientDt(IFX.SignonRq.ClientDt value) {
            this.clientDt = value;
        }

        /**
         * Gets the value of the clientApp property.
         * 
         * @return
         *     possible object is
         *     {@link IFX.SignonRq.ClientApp }
         *     
         */
        public IFX.SignonRq.ClientApp getClientApp() {
            return clientApp;
        }

        /**
         * Sets the value of the clientApp property.
         * 
         * @param value
         *     allowed object is
         *     {@link IFX.SignonRq.ClientApp }
         *     
         */
        public void setClientApp(IFX.SignonRq.ClientApp value) {
            this.clientApp = value;
        }

        /**
         * Gets the value of the computerId property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getComputerId() {
            return computerId;
        }

        /**
         * Sets the value of the computerId property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setComputerId(String value) {
            this.computerId = value;
        }

        /**
         * Gets the value of the institutionCode property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getInstitutionCode() {
            return institutionCode;
        }

        /**
         * Sets the value of the institutionCode property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setInstitutionCode(String value) {
            this.institutionCode = value;
        }


        /**
         * <p>Java class for anonymous complex type.
         * 
         * <p>The following schema fragment specifies the expected content contained within this class.
         * 
         * <pre>
         * &lt;complexType>
         *   &lt;complexContent>
         *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
         *       &lt;sequence>
         *         &lt;element name="Org" type="{http://www.w3.org/2001/XMLSchema}string"/>
         *         &lt;element name="Name" type="{http://www.w3.org/2001/XMLSchema}string"/>
         *         &lt;element name="Version" type="{http://www.w3.org/2001/XMLSchema}float"/>
         *         &lt;element name="ClientAppKey" type="{http://www.w3.org/2001/XMLSchema}string"/>
         *       &lt;/sequence>
         *     &lt;/restriction>
         *   &lt;/complexContent>
         * &lt;/complexType>
         * </pre>
         * 
         * 
         */
        @XmlAccessorType(XmlAccessType.FIELD)
        @XmlType(name = "", propOrder = {
            "org",
            "name",
            "version",
            "clientAppKey"
        })
        public static class ClientApp {

            @XmlElement(name = "Org", required = true)
            protected String org;
            @XmlElement(name = "Name", required = true)
            protected String name;
            @XmlElement(name = "Version")
            protected float version;
            @XmlElement(name = "ClientAppKey", required = true)
            protected String clientAppKey;

            /**
             * Gets the value of the org property.
             * 
             * @return
             *     possible object is
             *     {@link String }
             *     
             */
            public String getOrg() {
                return org;
            }

            /**
             * Sets the value of the org property.
             * 
             * @param value
             *     allowed object is
             *     {@link String }
             *     
             */
            public void setOrg(String value) {
                this.org = value;
            }

            /**
             * Gets the value of the name property.
             * 
             * @return
             *     possible object is
             *     {@link String }
             *     
             */
            public String getName() {
                return name;
            }

            /**
             * Sets the value of the name property.
             * 
             * @param value
             *     allowed object is
             *     {@link String }
             *     
             */
            public void setName(String value) {
                this.name = value;
            }

            /**
             * Gets the value of the version property.
             * 
             */
            public float getVersion() {
                return version;
            }

            /**
             * Sets the value of the version property.
             * 
             */
            public void setVersion(float value) {
                this.version = value;
            }

            /**
             * Gets the value of the clientAppKey property.
             * 
             * @return
             *     possible object is
             *     {@link String }
             *     
             */
            public String getClientAppKey() {
                return clientAppKey;
            }

            /**
             * Sets the value of the clientAppKey property.
             * 
             * @param value
             *     allowed object is
             *     {@link String }
             *     
             */
            public void setClientAppKey(String value) {
                this.clientAppKey = value;
            }

        }


        /**
         * <p>Java class for anonymous complex type.
         * 
         * <p>The following schema fragment specifies the expected content contained within this class.
         * 
         * <pre>
         * &lt;complexType>
         *   &lt;complexContent>
         *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
         *       &lt;sequence>
         *         &lt;element name="Year" type="{http://www.w3.org/2001/XMLSchema}short"/>
         *         &lt;element name="Month" type="{http://www.w3.org/2001/XMLSchema}byte"/>
         *         &lt;element name="Day" type="{http://www.w3.org/2001/XMLSchema}byte"/>
         *       &lt;/sequence>
         *     &lt;/restriction>
         *   &lt;/complexContent>
         * &lt;/complexType>
         * </pre>
         * 
         * 
         */
        @XmlAccessorType(XmlAccessType.FIELD)
        @XmlType(name = "", propOrder = {
            "year",
            "month",
            "day"
        })
        public static class ClientDt {

            @XmlElement(name = "Year")
            protected String year;
            @XmlElement(name = "Month")
            protected String month;
            @XmlElement(name = "Day")
            protected String day;

            /**
             * Gets the value of the year property.
             * 
             */
            public String getYear() {
                return year;
            }

            /**
             * Sets the value of the year property.
             * 
             */
            public void setYear(String value) {
                this.year = value;
            }

            /**
             * Gets the value of the month property.
             * 
             */
            public String getMonth() {
                return month;
            }

            /**
             * Sets the value of the month property.
             * 
             */
            public void setMonth(String value) {
                this.month = value;
            }

            /**
             * Gets the value of the day property.
             * 
             */
            public String getDay() {
                return day;
            }

            /**
             * Sets the value of the day property.
             * 
             */
            public void setDay(String value) {
                this.day = value;
            }

        }


        /**
         * <p>Java class for anonymous complex type.
         * 
         * <p>The following schema fragment specifies the expected content contained within this class.
         * 
         * <pre>
         * &lt;complexType>
         *   &lt;complexContent>
         *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
         *       &lt;sequence>
         *         &lt;element name="SignonRole" type="{http://www.w3.org/2001/XMLSchema}string"/>
         *         &lt;element name="CustId">
         *           &lt;complexType>
         *             &lt;complexContent>
         *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
         *                 &lt;sequence>
         *                   &lt;element name="SPName" type="{http://www.w3.org/2001/XMLSchema}string"/>
         *                   &lt;element name="CustLoginId" type="{http://www.w3.org/2001/XMLSchema}string"/>
         *                 &lt;/sequence>
         *               &lt;/restriction>
         *             &lt;/complexContent>
         *           &lt;/complexType>
         *         &lt;/element>
         *         &lt;element name="CustPswd">
         *           &lt;complexType>
         *             &lt;complexContent>
         *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
         *                 &lt;sequence>
         *                   &lt;element name="CryptType" type="{http://www.w3.org/2001/XMLSchema}string"/>
         *                   &lt;element name="Pswd" type="{http://www.w3.org/2001/XMLSchema}string"/>
         *                 &lt;/sequence>
         *               &lt;/restriction>
         *             &lt;/complexContent>
         *           &lt;/complexType>
         *         &lt;/element>
         *         &lt;element name="GenSessKey" type="{http://www.w3.org/2001/XMLSchema}byte"/>
         *       &lt;/sequence>
         *     &lt;/restriction>
         *   &lt;/complexContent>
         * &lt;/complexType>
         * </pre>
         * 
         * 
         */
        @XmlAccessorType(XmlAccessType.FIELD)
        @XmlType(name = "", propOrder = {
            "signonRole",
            "custId",
            "custPswd",
            "genSessKey"
        })
        public static class SignonPswd {

            @XmlElement(name = "SignonRole", required = true)
            protected String signonRole;
            @XmlElement(name = "CustId", required = true)
            protected IFX.SignonRq.SignonPswd.CustId custId;
            @XmlElement(name = "CustPswd", required = true)
            protected IFX.SignonRq.SignonPswd.CustPswd custPswd;
            @XmlElement(name = "GenSessKey")
            protected byte genSessKey;

            /**
             * Gets the value of the signonRole property.
             * 
             * @return
             *     possible object is
             *     {@link String }
             *     
             */
            public String getSignonRole() {
                return signonRole;
            }

            /**
             * Sets the value of the signonRole property.
             * 
             * @param value
             *     allowed object is
             *     {@link String }
             *     
             */
            public void setSignonRole(String value) {
                this.signonRole = value;
            }

            /**
             * Gets the value of the custId property.
             * 
             * @return
             *     possible object is
             *     {@link IFX.SignonRq.SignonPswd.CustId }
             *     
             */
            public IFX.SignonRq.SignonPswd.CustId getCustId() {
                return custId;
            }

            /**
             * Sets the value of the custId property.
             * 
             * @param value
             *     allowed object is
             *     {@link IFX.SignonRq.SignonPswd.CustId }
             *     
             */
            public void setCustId(IFX.SignonRq.SignonPswd.CustId value) {
                this.custId = value;
            }

            /**
             * Gets the value of the custPswd property.
             * 
             * @return
             *     possible object is
             *     {@link IFX.SignonRq.SignonPswd.CustPswd }
             *     
             */
            public IFX.SignonRq.SignonPswd.CustPswd getCustPswd() {
                return custPswd;
            }

            /**
             * Sets the value of the custPswd property.
             * 
             * @param value
             *     allowed object is
             *     {@link IFX.SignonRq.SignonPswd.CustPswd }
             *     
             */
            public void setCustPswd(IFX.SignonRq.SignonPswd.CustPswd value) {
                this.custPswd = value;
            }

            /**
             * Gets the value of the genSessKey property.
             * 
             */
            public byte getGenSessKey() {
                return genSessKey;
            }

            /**
             * Sets the value of the genSessKey property.
             * 
             */
            public void setGenSessKey(byte value) {
                this.genSessKey = value;
            }


            /**
             * <p>Java class for anonymous complex type.
             * 
             * <p>The following schema fragment specifies the expected content contained within this class.
             * 
             * <pre>
             * &lt;complexType>
             *   &lt;complexContent>
             *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
             *       &lt;sequence>
             *         &lt;element name="SPName" type="{http://www.w3.org/2001/XMLSchema}string"/>
             *         &lt;element name="CustLoginId" type="{http://www.w3.org/2001/XMLSchema}string"/>
             *       &lt;/sequence>
             *     &lt;/restriction>
             *   &lt;/complexContent>
             * &lt;/complexType>
             * </pre>
             * 
             * 
             */
            @XmlAccessorType(XmlAccessType.FIELD)
            @XmlType(name = "", propOrder = {
                "spName",
                "custLoginId"
            })
            public static class CustId {

                @XmlElement(name = "SPName", required = true)
                protected String spName;
                @XmlElement(name = "CustLoginId", required = true)
                protected String custLoginId;

                /**
                 * Gets the value of the spName property.
                 * 
                 * @return
                 *     possible object is
                 *     {@link String }
                 *     
                 */
                public String getSPName() {
                    return spName;
                }

                /**
                 * Sets the value of the spName property.
                 * 
                 * @param value
                 *     allowed object is
                 *     {@link String }
                 *     
                 */
                public void setSPName(String value) {
                    this.spName = value;
                }

                /**
                 * Gets the value of the custLoginId property.
                 * 
                 * @return
                 *     possible object is
                 *     {@link String }
                 *     
                 */
                public String getCustLoginId() {
                    return custLoginId;
                }

                /**
                 * Sets the value of the custLoginId property.
                 * 
                 * @param value
                 *     allowed object is
                 *     {@link String }
                 *     
                 */
                public void setCustLoginId(String value) {
                    this.custLoginId = value;
                }

            }


            /**
             * <p>Java class for anonymous complex type.
             * 
             * <p>The following schema fragment specifies the expected content contained within this class.
             * 
             * <pre>
             * &lt;complexType>
             *   &lt;complexContent>
             *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
             *       &lt;sequence>
             *         &lt;element name="CryptType" type="{http://www.w3.org/2001/XMLSchema}string"/>
             *         &lt;element name="Pswd" type="{http://www.w3.org/2001/XMLSchema}string"/>
             *       &lt;/sequence>
             *     &lt;/restriction>
             *   &lt;/complexContent>
             * &lt;/complexType>
             * </pre>
             * 
             * 
             */
            @XmlAccessorType(XmlAccessType.FIELD)
            @XmlType(name = "", propOrder = {
                "cryptType",
                "pswd"
            })
            public static class CustPswd {

                @XmlElement(name = "CryptType", required = true)
                protected String cryptType;
                @XmlElement(name = "Pswd", required = true)
                protected String pswd;

                /**
                 * Gets the value of the cryptType property.
                 * 
                 * @return
                 *     possible object is
                 *     {@link String }
                 *     
                 */
                public String getCryptType() {
                    return cryptType;
                }

                /**
                 * Sets the value of the cryptType property.
                 * 
                 * @param value
                 *     allowed object is
                 *     {@link String }
                 *     
                 */
                public void setCryptType(String value) {
                    this.cryptType = value;
                }

                /**
                 * Gets the value of the pswd property.
                 * 
                 * @return
                 *     possible object is
                 *     {@link String }
                 *     
                 */
                public String getPswd() {
                    return pswd;
                }

                /**
                 * Sets the value of the pswd property.
                 * 
                 * @param value
                 *     allowed object is
                 *     {@link String }
                 *     
                 */
                public void setPswd(String value) {
                    this.pswd = value;
                }

            }

        }

    }

}
