package com.encore.boc.extracts.bsr;

public class BSRActionConstants {

	public static String SUCCESS = "success";

	public static String GET_CUSTOMERDETAILS_QUERY = "SELECT a.GFCUS1,a.GFCUN,a.GFCPNC,a.GFGRP,a.GFCNAL,a.GFACO,a.GFCUB,a.GFCUS1_SBB,a.GFCUS1,b.C4CBQ,a.SOURCE,a.TICUSTLOC "
			+ "FROM GFPF  a INNER JOIN C4PF   b ON a.GFCTP1 = b.C4CTP1";

	public static String GET_CUSTOMERDETAILSCOUNT_QUERY = "select count(*) as result from gfpf where upper(gfcus1) = ? ";

	public static String GET_CUSTOMERLIMIT_QUERY = "SELECT DLTCATEGORY.DESCRIPTION AS CAT_DESC, DLTLIMITDETAIL.CURRENCY AS CURRENCY,"
			+ "ROUND((DLTLIMITDETAIL.AMOUNT/(SELECT POWER(10,C8PF.C8CED) FROM C8PF C8PF WHERE C8PF.C8CCY= DLTLIMITDETAIL.CURRENCY ) ),"
			+ " ( SELECT C8PF.C8CED FROM c8pf WHERE C8PF.C8CCY= DLTLIMITDETAIL.CURRENCY ) )  AS AMOUNT,"
			+ " DLTLIMITDETAIL.EXPIRES AS EXPIRY, DLTLIMITDETAIL.LCKEY      AS LCKEY,DLTLIMITDETAIL.SDKEY      AS SDKEY , "
			+ "TRIM(DLTLIMITCONTROL.DLCUSTOMER) || TRIM(DLTSTRUCTDETAIL.DLSTRUCTURE)|| DLTSTRUCTDETAIL.DLCATEGORY AS CATEGOERY ,"
			+ "DLTLIMITCONTROL.DLCUSTOMER AS LMTCUST FROM DLTLIMITCONTROL, DLTLIMITDETAIL,DLTSTRUCTDETAIL, DLTCATEGORY"
			+ " WHERE  DLTLIMITCONTROL.DLSTRUCTURE  = DLTSTRUCTDETAIL.DLSTRUCTURE AND "
			+ "DLTLIMITDETAIL.LCKEY = DLTLIMITCONTROL.KEY97 AND "
			+ "DLTLIMITDETAIL.SDKEY = DLTSTRUCTDETAIL.KEY97 AND "
			+ "DLTSTRUCTDETAIL.DLCATEGORY = DLTCATEGORY.DLCATEGORY AND "
			+ "DLTLIMITCONTROL.DLCUSTOMER = ? AND  "
			+ "DLTCATEGORY.DLSYSTEM      <> 'Y' AND "
			+ "DLTSTRUCTDETAIL.ENTRYTYPE = 'C' "
			+ "ORDER BY DLTSTRUCTDETAIL.SEQUENCER ASC";

	public static String GET_BSRDETAILS_INSERTION_QUERY = "insert into  BSR_DETAILS_STG (PLACE_UTILISATION_CREDIT_DISTCODE,"
			+ "PLACE_UTILISATION_CREDIT_POPGRPCODE,ORGANISATION_CODE,OCCUPATION_CODE,CATEGORY_BORROWER_CODE,"
			+ "ASSET_CLASSI_BORROWAL_ACCOUNT_CODE,SECURED_UNSECURED_LOAN_CODE,CATEGORY) "
			+ "values (?,?,?,?,?,?,?,?)";

	public static String GET_BSRDETAILS_UPDATION_QUERY = "UPDATE BSR_DETAILS_STG SET PLACE_UTILISATION_CREDIT_DISTCODE = ? ,	PLACE_UTILISATION_CREDIT_POPGRPCODE = ? ,	ORGANISATION_CODE = ? ,	"
			+ "OCCUPATION_CODE	= ? , CATEGORY_BORROWER_CODE	= ? , ASSET_CLASSI_BORROWAL_ACCOUNT_CODE	= ? , SECURED_UNSECURED_LOAN_CODE	= ? "
			+ " WHERE CATEGORY =? ";

	public static String GET_BSRDETAILS_DELETION_QUERY = "DELETE FROM BSR_DETAILS_STG WHERE CATEGORY =?";

	public static String GET_BSRDETAILS_COUNT_QUERY = "select count(*) as result from BSR_DETAILS_STG where upper(category)=?";

	public static String GET_BSRDETAILS_QUERY = "select PLACE_UTILISATION_CREDIT_DISTCODE,PLACE_UTILISATION_CREDIT_POPGRPCODE,"
			+ "ORGANISATION_CODE,OCCUPATION_CODE,CATEGORY_BORROWER_CODE,ASSET_CLASSI_BORROWAL_ACCOUNT_CODE,SECURED_UNSECURED_LOAN_CODE"
			+ "  FROM BSR_DETAILS_STG " + "where CATEGORY = ?";

	public static String GET_POPULATIONGROUPDETAILS_QUERY = "SELECT POPULATIONGROUPOFCENTRE,POPULATIONOFCENTRE,POPULATIONGROUPCODE FROM BSR_POPULATION_GROUP_STG WHERE POPULATIONGROUPOFCENTRE IS NOT NULL";

	public static String GET_DISTRICTDETAILS_QUERY = "SELECT DISTRICTNAME,DISTRICTCODE FROM BSR_DISTRICT_STG WHERE DISTRICTNAME IS NOT NULL";

	public static String GET_SECUNSECLOANCODEDETAILS_QUERY = "SELECT SECURITY_TYPE,SECURITY_TYPE_CODE FROM BSR_SEC_UNSEC_LOANS_STG WHERE SECURITY_TYPE IS NOT NULL";

	public static String GET_ASSETCLASSBORRACCOUNTDETAILS_QUERY = "SELECT ASSET_CLASSI_BORR_ACCT,ASSET_CLASSI_BORR_ACCT_CODE FROM BSR_ASSETCLASSI_BORROWAL_ACCOUNT_STG WHERE ASSET_CLASSI_BORR_ACCT IS NOT NULL";

	public static String GET_CATEGORYBORROWERCODEDETAILS_QUERY = "SELECT CATEGORY_BORROWER,CATEGORY_BORROWER_CODE FROM BSR_CATEGORY_BORROWER_STG WHERE CATEGORY_BORROWER IS NOT NULL";

	public static String GET_GETOCCUPATIONDETAILS_QUERY = "SELECT OCCUPATIONGROUP,OCCUPATIONSUBGROUP,OCCUPATIONCODE,OCCUPATIONDESCRIPTION FROM BSR_CLASSI_OCCUPATION_STG WHERE OCCUPATIONGROUP IS NOT NULL";

	public static String GET_ORGANISATIONTYPEDETAILS_QUERY = "SELECT TYPEOFORGANISATION,ORGANISATIONCODE FROM BSR_ORGANISATION_TYPE_STG WHERE TYPEOFORGANISATION IS NOT NULL";

}
