//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2016.10.27 at 01:02:20 PM IST 
//


package com.misys.tiplus2.apps.ti.service.common;

import javax.xml.bind.JAXBElement;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlElementRef;
import javax.xml.bind.annotation.XmlType;
import javax.xml.datatype.XMLGregorianCalendar;


/**
 * <p>Java class for GWRReportProfileSheduling complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="GWRReportProfileSheduling">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="PeriodAndDayInMonth" type="{urn:common.service.ti.apps.tiplus2.misys.com}GWRPeriodAndDayInMonth" minOccurs="0"/>
 *         &lt;element name="NextRunDate" type="{urn:common.service.ti.apps.tiplus2.misys.com}GWRDate" minOccurs="0"/>
 *         &lt;element name="Phase" type="{urn:common.service.ti.apps.tiplus2.misys.com}GWRBatchPhaseCode" minOccurs="0"/>
 *         &lt;element name="ReportRetentionPeriod" type="{urn:common.service.ti.apps.tiplus2.misys.com}GWRPeriod" minOccurs="0"/>
 *         &lt;element name="ReportActionType" type="{urn:common.service.ti.apps.tiplus2.misys.com}GWRReportAction" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "GWRReportProfileSheduling", propOrder = {
    "periodAndDayInMonth",
    "nextRunDate",
    "phase",
    "reportRetentionPeriod",
    "reportActionType"
})
public class GWRReportProfileSheduling {

    @XmlElement(name = "PeriodAndDayInMonth")
    protected GWRPeriodAndDayInMonth periodAndDayInMonth;
    @XmlElementRef(name = "NextRunDate", namespace = "urn:common.service.ti.apps.tiplus2.misys.com", type = JAXBElement.class)
    protected JAXBElement<XMLGregorianCalendar> nextRunDate;
    @XmlElementRef(name = "Phase", namespace = "urn:common.service.ti.apps.tiplus2.misys.com", type = JAXBElement.class)
    protected JAXBElement<String> phase;
    @XmlElement(name = "ReportRetentionPeriod")
    protected GWRPeriod reportRetentionPeriod;
    @XmlElement(name = "ReportActionType")
    protected GWRReportAction reportActionType;

    /**
     * Gets the value of the periodAndDayInMonth property.
     * 
     * @return
     *     possible object is
     *     {@link GWRPeriodAndDayInMonth }
     *     
     */
    public GWRPeriodAndDayInMonth getPeriodAndDayInMonth() {
        return periodAndDayInMonth;
    }

    /**
     * Sets the value of the periodAndDayInMonth property.
     * 
     * @param value
     *     allowed object is
     *     {@link GWRPeriodAndDayInMonth }
     *     
     */
    public void setPeriodAndDayInMonth(GWRPeriodAndDayInMonth value) {
        this.periodAndDayInMonth = value;
    }

    /**
     * Gets the value of the nextRunDate property.
     * 
     * @return
     *     possible object is
     *     {@link JAXBElement }{@code <}{@link XMLGregorianCalendar }{@code >}
     *     
     */
    public JAXBElement<XMLGregorianCalendar> getNextRunDate() {
        return nextRunDate;
    }

    /**
     * Sets the value of the nextRunDate property.
     * 
     * @param value
     *     allowed object is
     *     {@link JAXBElement }{@code <}{@link XMLGregorianCalendar }{@code >}
     *     
     */
    public void setNextRunDate(JAXBElement<XMLGregorianCalendar> value) {
        this.nextRunDate = value;
    }

    /**
     * Gets the value of the phase property.
     * 
     * @return
     *     possible object is
     *     {@link JAXBElement }{@code <}{@link String }{@code >}
     *     
     */
    public JAXBElement<String> getPhase() {
        return phase;
    }

    /**
     * Sets the value of the phase property.
     * 
     * @param value
     *     allowed object is
     *     {@link JAXBElement }{@code <}{@link String }{@code >}
     *     
     */
    public void setPhase(JAXBElement<String> value) {
        this.phase = value;
    }

    /**
     * Gets the value of the reportRetentionPeriod property.
     * 
     * @return
     *     possible object is
     *     {@link GWRPeriod }
     *     
     */
    public GWRPeriod getReportRetentionPeriod() {
        return reportRetentionPeriod;
    }

    /**
     * Sets the value of the reportRetentionPeriod property.
     * 
     * @param value
     *     allowed object is
     *     {@link GWRPeriod }
     *     
     */
    public void setReportRetentionPeriod(GWRPeriod value) {
        this.reportRetentionPeriod = value;
    }

    /**
     * Gets the value of the reportActionType property.
     * 
     * @return
     *     possible object is
     *     {@link GWRReportAction }
     *     
     */
    public GWRReportAction getReportActionType() {
        return reportActionType;
    }

    /**
     * Sets the value of the reportActionType property.
     * 
     * @param value
     *     allowed object is
     *     {@link GWRReportAction }
     *     
     */
    public void setReportActionType(GWRReportAction value) {
        this.reportActionType = value;
    }

}
