//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2016.10.27 at 01:02:20 PM IST 
//


package com.misys.tiplus2.apps.ti.service.common;

import javax.xml.bind.annotation.XmlEnum;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for GWRReportFileType.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * <p>
 * <pre>
 * &lt;simpleType name="GWRReportFileType">
 *   &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *     &lt;enumeration value="COMMASEPARATED"/>
 *     &lt;enumeration value="EXCEL"/>
 *     &lt;enumeration value="PDF"/>
 *     &lt;enumeration value="RPT"/>
 *     &lt;enumeration value="RTF"/>
 *     &lt;enumeration value="TEXT"/>
 *     &lt;enumeration value="WORD"/>
 *     &lt;maxLength value="30"/>
 *   &lt;/restriction>
 * &lt;/simpleType>
 * </pre>
 * 
 */
@XmlType(name = "GWRReportFileType")
@XmlEnum
public enum GWRReportFileType {

    COMMASEPARATED,
    EXCEL,
    PDF,
    RPT,
    RTF,
    TEXT,
    WORD;

    public String value() {
        return name();
    }

    public static GWRReportFileType fromValue(String v) {
        return valueOf(v);
    }

}
